import { iterateEntries } from "@common/utils";
import { Action, addObjectToStack, addVarToStack, createBytecode, createEmptyObjectVar, createJsonDeclaration, PCodeRep, setMember } from "@common/flash/avm1";
import { emitCrumbSwf } from "@common/flash/emitter";
import { LOCAL_PATHS, makeLocalPathsComposite } from "../game-data/local-paths";
import { SAFE_MESSAGES } from "../game-data/safe-messages";
import { MASCOT_MESSAGES } from "../game-data/mascot-messages";
import { TOUR_GUIDE_MESSAGES } from "../game-data/tour-guide-messages";
import { LANG } from "../game-data/lang";
import { FURNITURE } from "../game-logic/furniture";
import { IGLOO_FLOORING, IGLOO_TYPES } from "../game-logic/iglooItems";
import { ITEMS } from "../game-logic/items";
import serverList from "../servers";
import { GameData } from "@server/timelines/game-data";
import { StageScript } from "@server/game-data/stage-plays";
import { HuntCrumbs } from "@server/updates";
import { POSTCARD_CATALOGUE, POSTCARDS } from "@server/game-data/postcards";

function getLocalPaths(paths: Map<string, string>, useCompositePaths: boolean) {
  const code: PCodeRep = [];

  if (useCompositePaths) {
    const newPaths: Record<string, string> = {};
    paths.forEach((value, key) => {
      if (value !== undefined && value !== null) {
        newPaths[key] = value;
      }
    })
    const compositePaths = makeLocalPathsComposite({ ...LOCAL_PATHS, ...newPaths });
    iterateEntries(compositePaths, (key, value) => {
      const [base, path] = value;
      code.push(
        [Action.Push, "local_paths"],
        Action.GetVariable,
        [Action.Push, key, base],
        Action.GetVariable,
        [Action.Push, path],
        Action.Add2,
        Action.SetMember
      )
    });
  } else {
    [...Object.entries(LOCAL_PATHS), ...paths.entries()].forEach(([key, path]) => {
      if (path !== null && path !== undefined) {
        code.push(
          [Action.Push, "local_paths"],
          Action.GetVariable,
          [Action.Push, key],
          [Action.Push, path],
          Action.SetMember
        );
      }
    });
  }

  return code;
}

function getLinkPaths(isNewShell2009: boolean) {
  const code: PCodeRep = [];
  const useAffiliateLinks = !isNewShell2009;

  const linkPaths = useAffiliateLinks ? "master_link_paths" : "link_paths";

  if (useAffiliateLinks){
    code.push(
      [Action.Push, linkPaths],
      [Action.Push, 0],
      [Action.Push, "Object"],
      Action.NewObject,
      Action.DefineLocal,
      // miniclip paths would go here (see Apr 2009 local crumbs)
      [Action.Push, "link_paths"],
      Action.GetVariable,
      [Action.Push, 0],
      [Action.Push, linkPaths],
      Action.GetVariable,
      Action.SetMember
    )
  }

  code.push(
    [Action.Push, linkPaths],
    Action.GetVariable,
    [Action.Push, "main_web"],
    [Action.Push, "http://www.clubpenguin.com/"],
    Action.SetMember,
    [Action.Push, linkPaths],
    Action.GetVariable,
    [Action.Push, "client_web"],
    [Action.Push, "http://play.clubpenguin.com/"],
    Action.SetMember,
    [Action.Push, linkPaths],
    Action.GetVariable,
    [Action.Push, "cache_web"],
    [Action.Push, "http://support.clubpenguin.com/help/technical/clear_my_cache.htm"],
    Action.SetMember,
    [Action.Push, linkPaths],
    Action.GetVariable,
    [Action.Push, "connection_web"],
    [Action.Push, "http://support.clubpenguin.com/help/technical/lost_connection.htm"],
    Action.SetMember,
    [Action.Push, linkPaths],
    Action.GetVariable,
    [Action.Push, "cant_connect_web"],
    [Action.Push, "http://support.clubpenguin.com/help/technical/cant_connect_server.htm"],
    Action.SetMember,
    [Action.Push, linkPaths],
    Action.GetVariable,
    [Action.Push, "support_web"],
    [Action.Push, "http://support.clubpenguin.com/help/"],
    Action.SetMember,
    [Action.Push, linkPaths],
    Action.GetVariable,
    [Action.Push, "member_web"],
    [Action.Push, "http://www.clubpenguin.com/membership/"],
    Action.SetMember,
    [Action.Push, linkPaths],
    Action.GetVariable,
    [Action.Push, "manage_web"],
    [Action.Push, "https://secure.clubpenguin.com/manage_account/login.php"],
    Action.SetMember,
    [Action.Push, linkPaths],
    Action.GetVariable,
    [Action.Push, "community_web"],
    [Action.Push, "http://community.clubpenguin.com/"],
    Action.SetMember,
    [Action.Push, linkPaths],
    Action.GetVariable,
    [Action.Push, "guide_web"],
    [Action.Push, "http://www.clubpenguin.com/parents/club_penguin_guide.htm"],
    Action.SetMember,
    [Action.Push, linkPaths],
    Action.GetVariable,
    [Action.Push, "parents_web"],
    [Action.Push, "http://www.clubpenguin.com/parents/"],
    Action.SetMember,
    [Action.Push, linkPaths],
    Action.GetVariable,
    [Action.Push, "create_account_web"],
    [Action.Push, "http://play.clubpenguin.com/create_account/"],
    Action.SetMember,
    [Action.Push, linkPaths],
    Action.GetVariable,
    [Action.Push, "forgot_password_web"],
    [Action.Push, "http://support.clubpenguin.com/lost-password.php"],
    Action.SetMember,
    [Action.Push, linkPaths],
    Action.GetVariable,
    [Action.Push, "player_safety"],
    [Action.Push, "http://www.clubpenguin.com/parents/player_safety.htm"],
    Action.SetMember,
    [Action.Push, linkPaths],
    Action.GetVariable,
    [Action.Push, "fire_path_video_flv"],
    [Action.Push, "/play/card-jitsu/fire/videos/card-jitsu-fire-path.flv"],
    Action.SetMember,
    [Action.Push, linkPaths],
    Action.GetVariable,
    [Action.Push, "toys_web"],
    [Action.Push, "http://www.clubpenguin.com/toys/"],
    Action.SetMember,
    [Action.Push, linkPaths],
    Action.GetVariable,
    [Action.Push, "water_path_video_flv"],
    [Action.Push, "/play/card-jitsu/water/videos/card-jitsu-water-trailer.flv"],
    Action.SetMember
  );

    return code;
}

function getStageScript(script: StageScript) {
  const code: PCodeRep = [
    [Action.Push, "script_messages"],
    ...createJsonDeclaration(script),
    Action.DefineLocal
  ];

  return code;
}

function getHuntCrumbs(hunt: HuntCrumbs | null) {
  const code: PCodeRep = [];

  if (hunt !== null) {
    code.push(
      [Action.Push, "lang"],
      Action.GetVariable,
      [Action.Push, "scavenger_hunt", hunt.lang.en.loading],
      Action.SetMember,
      [Action.Push, "lang"],
      Action.GetVariable,
      [Action.Push, "title", hunt.lang.en.title],
      Action.SetMember,
      [Action.Push, "lang"],
      Action.GetVariable,
      [Action.Push, "start_string", hunt.lang.en.start],
      Action.SetMember,
      [Action.Push, "lang"],
      Action.GetVariable,
      [Action.Push, "scavenger_items_found", hunt.lang.en.itemsFound],
      Action.SetMember,
      [Action.Push, "lang"],
      Action.GetVariable,
      [Action.Push, "scavenger_items_found_plural", hunt.lang.en.itemsFoundPlural],
      Action.SetMember,
      [Action.Push, "lang"],
      Action.GetVariable,
      [Action.Push, "claim_prize", hunt.lang.en.claim],
      Action.SetMember,
      [Action.Push, "lang"],
      Action.GetVariable,
      [Action.Push, "continue", hunt.lang.en.continue],
      Action.SetMember,
      [Action.Push, "lang"],
      Action.GetVariable,
      [Action.Push, "clue0", hunt.lang.en.clues[0]],
      Action.SetMember,
      [Action.Push, "lang"],
      Action.GetVariable,
      [Action.Push, "clue1", hunt.lang.en.clues[1]],
      Action.SetMember,
      [Action.Push, "lang"],
      Action.GetVariable,
      [Action.Push, "clue2", hunt.lang.en.clues[2]],
      Action.SetMember,
      [Action.Push, "lang"],
      Action.GetVariable,
      [Action.Push, "clue3", hunt.lang.en.clues[3]],
      Action.SetMember,
      [Action.Push, "lang"],
      Action.GetVariable,
      [Action.Push, "clue4", hunt.lang.en.clues[4]],
      Action.SetMember,
      [Action.Push, "lang"],
      Action.GetVariable,
      [Action.Push, "clue5", hunt.lang.en.clues[5]],
      Action.SetMember,
      [Action.Push, "lang"],
      Action.GetVariable,
      [Action.Push, "clue6", hunt.lang.en.clues[6]],
      Action.SetMember,
      [Action.Push, "lang"],
      Action.GetVariable,
      [Action.Push, "clue7", hunt.lang.en.clues[7]],
      Action.SetMember
    )
  }

  return code;
}

function getLang(): PCodeRep {
  const code: PCodeRep = [];

  iterateEntries(LANG, (key, lang) => {
    code.push(
      [Action.Push, "lang"],
      Action.GetVariable,
      [Action.Push, key, lang],
      Action.SetMember
    );
  });

  return code;
}

function getFurnitureCrumbs() {
  const code: PCodeRep = [];

  FURNITURE.rows.forEach(row => {
    code.push(
      [Action.Push, "furniture_crumbs"],
      Action.GetVariable,
      [Action.Push, row.id],
      [Action.Push, "name"],
      [Action.Push, row.name],
      [Action.Push, 1],
      Action.InitObject,
      Action.SetMember
    )
  });

  return code;
}

function getFloorCrumbs() {
  const code: PCodeRep = [];

  IGLOO_FLOORING.rows.forEach(row => {
    code.push(
      [Action.Push, "floor_crumbs"],
      Action.GetVariable,
      [Action.Push, row.id],
      [Action.Push, "name"],
      [Action.Push, row.name],
      [Action.Push, 1],
      Action.InitObject,
      Action.SetMember
    )
  });

  return code;
}

function getPaperCrumbs() {
  const code: PCodeRep = [];

  ITEMS.rows.forEach(row => {
    code.push(
      [Action.Push, "paper_crumbs"],
      Action.GetVariable,
      [Action.Push, row.id],
      [Action.Push, "name"],
      [Action.Push, row.name],
      [Action.Push, 1],
      Action.InitObject,
      Action.SetMember
    )
  });

  return code;
}

function getIglooCrumbs() {
  const code: PCodeRep = [];

  IGLOO_TYPES.rows.forEach(row => {
    code.push(
      [Action.Push, "igloo_crumbs"],
      Action.GetVariable,
      [Action.Push, row.id],
      [Action.Push, "name"],
      [Action.Push, row.name],
      [Action.Push, 1],
      Action.InitObject,
      Action.SetMember
    )
  });

  return code;
}

function getServerCrumbs() {
  const code: PCodeRep = [
    [Action.Push, "servers"],
    [Action.Push, 0],
    [Action.Push, "Object"],
    Action.NewObject,
    Action.DefineLocal
  ];

  serverList.forEach(server => {
    code.push(
      [Action.Push, "servers"],
      Action.GetVariable,
      [Action.Push, server.id],
      [Action.Push, "name"],
      [Action.Push, server.name],
      [Action.Push, 1],
      Action.InitObject,
      Action.SetMember
    )
  })

  return code;
}

function getLangError(): PCodeRep {
  return [
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "KICK"],
    Action.GetMember,
    [Action.Push, "A moderator has removed you from this server. Please be careful what you say and do online and remember to follow the Club Penguin rules."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "MODERATOR_BAN"],
    Action.GetMember,
    [Action.Push, "A moderator has banned your account. Your ban will expire in: %number% hours"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "GAME_CHEAT"],
    Action.GetMember,
    [Action.Push, "The system has automatically removed you from the server. Please be careful what you say and do online and remember to follow the Club Penguin rules."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "AUTO_BAN"],
    Action.GetMember,
    [Action.Push, "<b>Banned:</b>\nThe server has automatically banned you for saying a bad word.\nYou Said: \"%badword%\""],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "BAN_DURATION"],
    Action.GetMember,
    [Action.Push, "<b>Banned:</b>\nYou are banned for the next %0 %1"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "BAN_FOREVER"],
    Action.GetMember,
    [Action.Push, "<b>Banned:</b>\nYou are banned forever"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "BAN_AN_HOUR"],
    Action.GetMember,
    [Action.Push, "<b>Banned:</b>\nYour ban will expire within the hour"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "HACKING_AUTO_BAN"],
    Action.GetMember,
    [Action.Push, "<b>Banned:<>\nThe server has automatically banned you.\nReason: \"%reason%\""],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "BUDDY_LIMIT"],
    Action.GetMember,
    [Action.Push, "Sorry, you may only have %number% buddies. Please remove some buddies to add more"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "TIME_WARNING"],
    Action.GetMember,
    [Action.Push, "You have %number% minutes remaining on the Club Penguin Timer. Have fun!"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "NO_PLAY_TIME"],
    Action.GetMember,
    [Action.Push, "Time's up. Thanks for playing! Check out the <b>%0Community%1</b> section of the website for fun ways to spend your time outside of Club Penguin."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "PLAY_TIME_OVER"],
    Action.GetMember,
    [Action.Push, "Time's up. Thanks for playing! Check out the <b>%0Community%1</b> section of the website for fun ways to spend your time outside of Club Penguin."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "OUT_PLAY_TIME"],
    Action.GetMember,
    [Action.Push, "You can only play between the hours of %0 and %1."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "GROUNDED"],
    Action.GetMember,
    [Action.Push, "You cannot play because you're currently grounded."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "PLAYER_IN_ROOM"],
    Action.GetMember,
    [Action.Push, "Please exit your game before leaving the room"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "DEFAULT_ERROR"],
    Action.GetMember,
    [Action.Push, "There was an error"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "TIME_OUT"],
    Action.GetMember,
    [Action.Push, "Auto Disconnect, your penguin has been idle for more than 10 minutes"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "CONNECTION_LOST"],
    Action.GetMember,
    [Action.Push, "Connection was lost.\nPlease click to learn more"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "LOAD_ERROR"],
    Action.GetMember,
    [Action.Push, "<b>Load Error</b>\nPlease clear your cache and try again"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "MULTI_CONNECTIONS"],
    Action.GetMember,
    [Action.Push, "You can only have one Club Penguin window open at a time. Please close any other windows and tabs in your internet browser to connect."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "ACCOUNT_NOT_ACTIVATE"],
    Action.GetMember,
    [Action.Push, "Your account has not been activated"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "NO_CONNECTION"],
    Action.GetMember,
    [Action.Push, "Having trouble connecting? Please try again, or contact support if the problem continues."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "ITEM_NOT_EXIST"],
    Action.GetMember,
    [Action.Push, "This item is not currently available."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "CONNECTION_TIMEOUT"],
    Action.GetMember,
    [Action.Push, "Connection timeout. Please choose another server or try again later."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "MAX_IGLOO_FURNITURE_ERROR"],
    Action.GetMember,
    [Action.Push, "Sorry, your igloo may only contain %number% items. Please remove an item to add this item."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "NOT_MEMBER"],
    Action.GetMember,
    [Action.Push, "Oops! You need to purchase a membership to buy %type%. We would love to have you join. Click the button below to see more about membership"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "PASSWORD_REQUIRED"],
    Action.GetMember,
    [Action.Push, "You must provide your password \nto enter Club Penguin"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "PASSWORD_SHORT"],
    Action.GetMember,
    [Action.Push, "Your password is too short. \nPlease try again"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "PASSWORD_LONG"],
    Action.GetMember,
    [Action.Push, "Your password is too long. \nPlease try again"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "PASSWORD_WRONG"],
    Action.GetMember,
    [Action.Push, "Incorrect Password. \nNOTE: Passwords are CaSe SeNsiTIVE"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "PUFFLE_LIMIT_M"],
    Action.GetMember,
    [Action.Push, "Sorry, you may only have a maximum of %number% puffles"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "PUFFLE_LIMIT_NM"],
    Action.GetMember,
    [Action.Push, "Sorry, you must be a member to have more than %number% puffles"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "NAME_NOT_ALLOWED"],
    Action.GetMember,
    [Action.Push, "Sorry, this name is not available. Please try again"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "REDEMPTION_CONNECTION_LOST"],
    Action.GetMember,
    [Action.Push, "Lost connection. If you have not clicked \"Done\", you can reuse this code at another time."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "REDEMPTION_ALREADY_HAVE_ITEM"],
    Action.GetMember,
    [Action.Push, "You already have this item."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "REDEMPTION_SERVER_FULL"],
    Action.GetMember,
    [Action.Push, "The server is full. Please try again later."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "REDEMPTION_BOOK_ID_NOT_EXIST"],
    Action.GetMember,
    [Action.Push, "That book does not exist."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "REDEMPTION_BOOK_ALREADY_REDEEMED"],
    Action.GetMember,
    [Action.Push, "You have already unlocked this book."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "REDEMPTION_WRONG_BOOK_ANSWER"],
    Action.GetMember,
    [Action.Push, "You have entered an incorrect answer."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "REDEMPTION_BOOK_TOO_MANY_ATTEMPTS"],
    Action.GetMember,
    [Action.Push, "An incorrect answer has been entered 5 times. Please try again later."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "REDEMPTION_CODE_NOT_FOUND"],
    Action.GetMember,
    [Action.Push, "The code you have entered is incorrect."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "REDEMPTION_CODE_ALREADY_REDEEMED"],
    Action.GetMember,
    [Action.Push, "The code you entered has already been used."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "REDEMPTION_TOO_MANY_ATTEMPTS"],
    Action.GetMember,
    [Action.Push, "An incorrect code has been entered 5 times. Please try again in\n45 minutes."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "REDEMPTION_CATALOG_NOT_AVAILABLE"],
    Action.GetMember,
    [Action.Push, "Sorry, the catalog you're looking for is not available yet. Please try again at a later date."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "REDEMPTION_PUFFLES_MAX"],
    Action.GetMember,
    [Action.Push, "You already have the maximum number of puffles."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "REDEMPTION_PUFFLE_INVALID"],
    Action.GetMember,
    [Action.Push, "Please choose a different puffle name."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "REDEMPTION_PUFFLE_CODE_MAX"],
    Action.GetMember,
    [Action.Push, "You can only redeem one puffle per code."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "REDEMPTION_CODE_TOO_SHORT"],
    Action.GetMember,
    [Action.Push, "The code is too short.\nIt must be at least 9 characters."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "REDEMPTION_CODE_TOO_LONG"],
    Action.GetMember,
    [Action.Push, "The code is too long.\nIt must be 16 characters or shorter."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "REDEMPTION_NO_EXCLUSIVE_REDEEMS"],
    Action.GetMember,
    [Action.Push, "You've chosen all of your Super Exclusive bonus items."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "REDEMPTION_CODE_GROUP_REDEEMED"],
    Action.GetMember,
    [Action.Push, "Only one code containing 2500 coins can be redeemed per account."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "REDEMPTION_CODE_EXPIRED"],
    Action.GetMember,
    [Action.Push, "The code you have entered has expired"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "GOLDEN_CODE_NOT_READY"],
    Action.GetMember,
    [Action.Push, "You'll be able to redeem this code Nov. 25. Please come back then..."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "ITEM_IN_HOUSE"],
    Action.GetMember,
    [Action.Push, "You already have this item"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "NOT_ENOUGH_COINS"],
    Action.GetMember,
    [Action.Push, "You need more coins"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "NOT_ENOUGH_MEDALS"],
    Action.GetMember,
    [Action.Push, "You don't have enough medals to obtain this item."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "NAME_REQUIRED"],
    Action.GetMember,
    [Action.Push, "You must provide your Penguin Name to enter Club Penguin"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "NAME_SHORT"],
    Action.GetMember,
    [Action.Push, "Your Penguin Name is too short. Please try again"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "NAME_LONG"],
    Action.GetMember,
    [Action.Push, "Your Penguin Name is too long. Please try again"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "NAME_NOT_FOUND"],
    Action.GetMember,
    [Action.Push, "Penguin not found. Try Again?"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "LOGIN_FAILED"],
    Action.GetMember,
    [Action.Push, "Login Failed, please try at a later time"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "LOGIN_FLOODING_DAILY"],
    Action.GetMember,
    [Action.Push, "Maximum login attempts exceeded. Please try again in an hour"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "LOGIN_FLOODING"],
    Action.GetMember,
    [Action.Push, "Maximum login attempts exceeded. Please try again in an hour"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "PASSWORD_SAVE_PROMPT"],
    Action.GetMember,
    [Action.Push, "Do not use this feature if\nyou are using a school, library,\nor public computer.\n\nAnyone that uses this computer will have access to your penguin."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "SERVER_FULL"],
    Action.GetMember,
    [Action.Push, "Sorry this server is full. Please select another server."],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "ROOM_FULL"],
    Action.GetMember,
    [Action.Push, "Sorry this room is currently full"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "GAME_FULL"],
    Action.GetMember,
    [Action.Push, "Sorry, this game is full. Check back in a little while. Thank you for your patience!"],
    Action.SetMember,
    [Action.Push, "error_lang"],
    Action.GetVariable,
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "MAX_STAMPBOOK_COVER_ITEMS"],
    Action.GetMember,
    [Action.Push, "Only %number% items can be stuck on the cover at once."],
    Action.SetMember
  ];
}

const getPostcardCrumbs = (): PCodeRep => {
  const catalogue = new Set(POSTCARD_CATALOGUE);
  const toUse = POSTCARDS.filter(p => catalogue.has(p.id));
  return [
    new Array(8).fill(0).flatMap((_, index) => {
      const category = index + 1;
      const postcards = toUse.filter(p => p.category === category);
      const varName = `category_0${category}`;
      return [
        ...createEmptyObjectVar(varName),
        ...postcards.flatMap((postcard) => setMember(addVarToStack(varName), postcard.id, addObjectToStack({
          subject: postcard.subject,
          in_catalog: true
        })))
      ];
    }),
    createEmptyObjectVar('pc_crumbs'),
    setMember(addVarToStack('pc_crumbs'), 'EPF', addVarToStack('category_01')),
    setMember(addVarToStack('pc_crumbs'), 'Featured Postcards', addVarToStack('category_02')),
    setMember(addVarToStack('pc_crumbs'), 'Friendship', addVarToStack('category_03')),
    setMember(addVarToStack('pc_crumbs'), 'Puffles', addVarToStack('category_04')),
    setMember(addVarToStack('pc_crumbs'), 'Party', addVarToStack('category_05')),
    setMember(addVarToStack('pc_crumbs'), 'Games', addVarToStack('category_06')),
    setMember(addVarToStack('pc_crumbs'), 'Rooms', addVarToStack('category_07')),
    setMember(addVarToStack('pc_crumbs'), 'From us', addVarToStack('category_08'))
  ].flat();
}

export function getLocalCrumbsSwf(d: GameData): Buffer {
  // hardcoded hex dump of the function's bytecode
  const treverseMessages = [
    0x8e, 0x1e, 0x00, 0x74, 0x72, 0x65, 0x76, 0x65, 
    0x72, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 
    0x67, 0x65, 0x73, 0x00, 0x01, 0x00, 0x04, 0x2a, 
    0x00, 0x01, 0x6e, 0x6f, 0x64, 0x65, 0x00, 0xbf, 
    0x00, 0x96, 0x02, 0x00, 0x04, 0x01, 0x55, 0x87, 
    0x01, 0x00, 0x00, 0x96, 0x01, 0x00, 0x02, 0x49, 
    0x9d, 0x02, 0x00, 0xab, 0x00, 0x96, 0x02, 0x00, 
    0x04, 0x00, 0x87, 0x01, 0x00, 0x03, 0x17, 0x96, 
    0x04, 0x00, 0x04, 0x01, 0x04, 0x03, 0x4e, 0x96, 
    0x04, 0x00, 0x00, 0x69, 0x64, 0x00, 0x4e, 0x87, 
    0x01, 0x00, 0x02, 0x17, 0x96, 0x1d, 0x00, 0x00, 
    0x74, 0x72, 0x65, 0x76, 0x65, 0x72, 0x65, 0x73, 
    0x65, 0x64, 0x5f, 0x73, 0x61, 0x66, 0x65, 0x5f, 
    0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 
    0x6f, 0x62, 0x6a, 0x00, 0x1c, 0x96, 0x06, 0x00, 
    0x04, 0x02, 0x04, 0x01, 0x04, 0x03, 0x4e, 0x4f, 
    0x96, 0x04, 0x00, 0x04, 0x01, 0x04, 0x03, 0x4e, 
    0x96, 0x06, 0x00, 0x00, 0x6d, 0x65, 0x6e, 0x75, 
    0x00, 0x4e, 0x96, 0x08, 0x00, 0x00, 0x6c, 0x65, 
    0x6e, 0x67, 0x74, 0x68, 0x00, 0x4e, 0x96, 0x05, 
    0x00, 0x07, 0x00, 0x00, 0x00, 0x00, 0x67, 0x12, 
    0x9d, 0x02, 0x00, 0x2e, 0x00, 0x96, 0x04, 0x00, 
    0x04, 0x01, 0x04, 0x03, 0x4e, 0x96, 0x06, 0x00, 
    0x00, 0x6d, 0x65, 0x6e, 0x75, 0x00, 0x4e, 0x96, 
    0x17, 0x00, 0x07, 0x01, 0x00, 0x00, 0x00, 0x00, 
    0x74, 0x72, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 
    0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 
    0x00, 0x3d, 0x17, 0x99, 0x02, 0x00, 0x47, 0xff
  ];

  const code: PCodeRep = [
    [Action.Push, "shell"],
    [Action.Push, 0],
    [Action.Push, "_global"],
    Action.GetVariable,
    [Action.Push, "getCurrentShell"],
    Action.CallMethod,
    Action.DefineLocal,
    [Action.Push, "root_path"],
    [Action.Push, 0],
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "getRootPath"],
    Action.CallMethod,
    Action.DefineLocal,
    [Action.Push, "language_folder"],
    [Action.Push, 0],
    [Action.Push, "shell"],
    Action.GetVariable,
    [Action.Push, "getLocalizedFolder"],
    Action.CallMethod,
    Action.DefineLocal,
    [Action.Push, "local_content"],
    [Action.Push, "root_path"],
    Action.GetVariable,
    [Action.Push, "content/local/"],
    Action.Add2,
    [Action.Push, "language_folder"],
    Action.GetVariable,
    Action.Add2,
    Action.DefineLocal,
    [Action.Push, "website_content"],
    [Action.Push, "root_path"],
    Action.GetVariable,
    Action.DefineLocal,
    [Action.Push, "blocked_prefixes"],
    [Action.Push, 0],
    Action.InitArray,
    Action.DefineLocal,
    [Action.Push, "blocked_suffixes"],
    [Action.Push, 0],
    Action.InitArray,
    Action.DefineLocal,
    [Action.Push, "blocked_overrides"],
    [Action.Push, 0],
    Action.InitArray,
    Action.DefineLocal,
    [Action.Push, "sensei"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "room_"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "map"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "login"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "igloo"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "select"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "archive"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "current_news"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "old_news"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "mission"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "_catalogue"],
    [Action.Push, 1],
    [Action.Push, "blocked_suffixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "card"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "ninja"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "cart"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "sled"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "waves"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "firesensi"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "fire"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "hyrdo"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "pizzatron"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "dancing"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "library"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "fish"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "beans"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "jetpack"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "thinice"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "mixmaster"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "aqua"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "roundup"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "astro"],
    [Action.Push, 1],
    [Action.Push, "blocked_prefixes"],
    Action.GetVariable,
    [Action.Push, "push"],
    Action.CallMethod,
    Action.Pop,
    [Action.Push, "local_paths"],
    [Action.Push, 0],
    [Action.Push, "Object"],
    Action.NewObject,
    Action.DefineLocal,
    ...getLocalPaths(d.getLocalPaths(), d.useCompositePaths()),
    [Action.Push, "link_paths"],
    [Action.Push, 0],
    [Action.Push, "Object"],
    Action.NewObject,
    Action.DefineLocal,
    ...getLinkPaths(d.isNewShell2009()),
    [Action.Push, "lang"],
    [Action.Push, 0],
    [Action.Push, "Object"],
    Action.NewObject,
    Action.DefineLocal,
    [Action.Push, "error_lang"],
    [Action.Push, 0],
    [Action.Push, "Object"],
    Action.NewObject,
    Action.DefineLocal,
    ...getLangError(),
    ...getLang(),
    [Action.Push, "quick_messages"],
    [Action.Push, "Ok"],
    [Action.Push, "No"],
    [Action.Push, "Yes"],
    [Action.Push, "Bye"],
    [Action.Push, "Hello"],
    [Action.Push, 5],
    [Action.Push, "Array"],
    Action.NewObject,
    Action.DefineLocal,
    [Action.Push, "safe_messages"],
    ...createJsonDeclaration(SAFE_MESSAGES),
    Action.DefineLocal,
    [Action.Push, "treveresed_safe_message_obj"],
    [Action.Push, 0],
    [Action.Push, "Object"],
    Action.NewObject,
    Action.DefineLocal,
    [Action.Push, "safe_messages"],
    Action.GetVariable,
    [Action.Push, 1],
    [Action.Push, "treverseMessages"],
    Action.CallFunction,
    Action.Pop,
    [Action.Push, "bandScript1"],
    [Action.Push, "category"],
    [Action.Push, "Band Script 1"],
    [Action.Push, "categoryActive"],
    [Action.Push, false],
    [Action.Push, "sharedScript"],
    [Action.Push, true],
    [Action.Push, "script"],
    [Action.Push, "name"],
    [Action.Push, "G Billy"],
    [Action.Push, "message"],
    [Action.Push, "I'm going to start planning our next recording session."],
    [Action.Push, 2],
    Action.InitObject,
    [Action.Push, "name"],
    [Action.Push, "Franky"],
    [Action.Push, "message"],
    [Action.Push, "I need to spend a bit of time with my guitar."],
    [Action.Push, 2],
    Action.InitObject,
    [Action.Push, "name"],
    [Action.Push, "Petey K"],
    [Action.Push, "message"],
    [Action.Push, "It's been an emotional day."],
    [Action.Push, 2],
    Action.InitObject,
    [Action.Push, "name"],
    [Action.Push, "Stompin Bob"],
    [Action.Push, "message"],
    [Action.Push, "Probably just chillax for a while."],
    [Action.Push, 2],
    Action.InitObject,
    [Action.Push, "name"],
    [Action.Push, "Franky"],
    [Action.Push, "message"],
    [Action.Push, "What are you going to do now?"],
    [Action.Push, 2],
    Action.InitObject,
    [Action.Push, "name"],
    [Action.Push, "Stompin Bob"],
    [Action.Push, "message"],
    [Action.Push, "Yeah, I could feel the rhythm in my flippers."],
    [Action.Push, 2],
    Action.InitObject,
    [Action.Push, "name"],
    [Action.Push, "Franky"],
    [Action.Push, "message"],
    [Action.Push, "It was awesome.  The crowd was really getting into it!"],
    [Action.Push, 2],
    Action.InitObject,
    [Action.Push, "name"],
    [Action.Push, "Petey K"],
    [Action.Push, "message"],
    [Action.Push, "That gig was unbelievable.  And I was brilliant!"],
    [Action.Push, 2],
    Action.InitObject,
    [Action.Push, "name"],
    [Action.Push, "G Billy"],
    [Action.Push, "message"],
    [Action.Push, "Good work guys.  We really rocked out there!"],
    [Action.Push, 2],
    Action.InitObject,
    [Action.Push, 9],
    Action.InitArray,
    [Action.Push, 4],
    Action.InitObject,
    Action.DefineLocal,
    [Action.Push, "mascot_messages"],
    ...createJsonDeclaration(MASCOT_MESSAGES),
    Action.DefineLocal,
    [Action.Push, "tour_guide_messages"],
    ...createJsonDeclaration(TOUR_GUIDE_MESSAGES),
    Action.DefineLocal,
    [Action.Push, "jokes"],
    [Action.Push, "What do you call a fish with no eyes?|FSH"],
    [Action.Push, "Why do penguins eat fish?|Because donuts get soggy before they can catch them"],
    [Action.Push, "What lies at the bottom of the sea and shakes?|A nervous wreck!"],
    [Action.Push, "Why is it so easy to weigh fish?|They have their own scales"],
    [Action.Push, "What do Penguins sing on a birthday?|Freeze a jolly good fellow"],
    [Action.Push, "How do you communicate with a fish?|You drop him a line"],
    [Action.Push, "What is a penguin's favourite party game?|Sardines"],
    [Action.Push, "Why are igloos round?|So that penguins can't hide in the corners"],
    [Action.Push, "How does a penguin build its house?|Igloos it together"],
    [Action.Push, "Why are penguins so popular on the Internet?|Because they have Web feet!"],
    [Action.Push, "What do you call a penguin in the desert?|Lost"],
    [Action.Push, "Why don´t you see Penguins in Britain?|Because they´re afraid of Wales"],
    [Action.Push, "What´s black and white and goes round and round?|A penguin in a revolving door"],
    [Action.Push, "What bird can write underwater?|A ball point PENguin!"],
    [Action.Push, "What's the best way to catch a fish?|Have someone throw it at you"],
    [Action.Push, 15],
    [Action.Push, "Array"],
    Action.NewObject,
    Action.DefineLocal,
    [Action.Push, "furniture_crumbs"],
    [Action.Push, 0],
    [Action.Push, "Object"],
    Action.NewObject,
    Action.DefineLocal,
    ...getFurnitureCrumbs(),
    [Action.Push, "floor_crumbs"],
    [Action.Push, 0],
    [Action.Push, "Object"],
    Action.NewObject,
    Action.DefineLocal,
    ...getFloorCrumbs(),
    [Action.Push, "paper_crumbs"],
    [Action.Push, 0],
    [Action.Push, "Object"],
    Action.NewObject,
    Action.DefineLocal,
    ...getPaperCrumbs(),
    [Action.Push, "igloo_crumbs"],
    [Action.Push, 0],
    [Action.Push, "Object"],
    Action.NewObject,
    Action.DefineLocal,
    ...getIglooCrumbs(),
    [Action.Push, "puffle_crumbs"],
    [Action.Push, 0],
    [Action.Push, "Object"],
    Action.NewObject,
    Action.DefineLocal,
    [Action.Push, "puffle_crumbs"],
    Action.GetVariable,
    [Action.Push, 0],
    [Action.Push, "name"],
    [Action.Push, "Blue"],
    [Action.Push, 1],
    Action.InitObject,
    Action.SetMember,
    [Action.Push, "puffle_crumbs"],
    Action.GetVariable,
    [Action.Push, 1],
    [Action.Push, "name"],
    [Action.Push, "Pink"],
    [Action.Push, 1],
    Action.InitObject,
    Action.SetMember,
    [Action.Push, "puffle_crumbs"],
    Action.GetVariable,
    [Action.Push, 2],
    [Action.Push, "name"],
    [Action.Push, "Black"],
    [Action.Push, 1],
    Action.InitObject,
    Action.SetMember,
    [Action.Push, "puffle_crumbs"],
    Action.GetVariable,
    [Action.Push, 3],
    [Action.Push, "name"],
    [Action.Push, "Green"],
    [Action.Push, 1],
    Action.InitObject,
    Action.SetMember,
    [Action.Push, "puffle_crumbs"],
    Action.GetVariable,
    [Action.Push, 4],
    [Action.Push, "name"],
    [Action.Push, "Purple"],
    [Action.Push, 1],
    Action.InitObject,
    Action.SetMember,
    [Action.Push, "puffle_crumbs"],
    Action.GetVariable,
    [Action.Push, 5],
    [Action.Push, "name"],
    [Action.Push, "Red"],
    [Action.Push, 1],
    Action.InitObject,
    Action.SetMember,
    [Action.Push, "puffle_crumbs"],
    Action.GetVariable,
    [Action.Push, 6],
    [Action.Push, "name"],
    [Action.Push, "Yellow"],
    [Action.Push, 1],
    Action.InitObject,
    Action.SetMember,
    [Action.Push, "puffle_crumbs"],
    Action.GetVariable,
    [Action.Push, 7],
    [Action.Push, "name"],
    [Action.Push, "White"],
    [Action.Push, 1],
    Action.InitObject,
    Action.SetMember,
    [Action.Push, "puffle_crumbs"],
    Action.GetVariable,
    [Action.Push, 8],
    [Action.Push, "name"],
    [Action.Push, "Orange"],
    [Action.Push, 1],
    Action.InitObject,
    Action.SetMember,
    ...getPostcardCrumbs(),
    [Action.Push, "hunt_crumbs"],
    [Action.Push, 0],
    [Action.Push, "Array"],
    Action.NewObject,
    Action.DefineLocal,
    [Action.Push, "hunt_crumbs"],
    Action.GetVariable,
    [Action.Push, 0],
    [Action.Push, "name"],
    [Action.Push, "cave"],
    [Action.Push, "is_found"],
    [Action.Push, false],
    [Action.Push, "is_required"],
    [Action.Push, true],
    [Action.Push, 3],
    Action.InitObject,
    Action.SetMember,
    [Action.Push, "hunt_crumbs"],
    Action.GetVariable,
    [Action.Push, 1],
    [Action.Push, "name"],
    [Action.Push, "cove"],
    [Action.Push, "is_found"],
    [Action.Push, false],
    [Action.Push, "is_required"],
    [Action.Push, true],
    [Action.Push, 3],
    Action.InitObject,
    Action.SetMember,
    [Action.Push, "hunt_crumbs"],
    Action.GetVariable,
    [Action.Push, 2],
    [Action.Push, "name"],
    [Action.Push, "dock"],
    [Action.Push, "is_found"],
    [Action.Push, false],
    [Action.Push, "is_required"],
    [Action.Push, true],
    [Action.Push, 3],
    Action.InitObject,
    Action.SetMember,
    [Action.Push, "hunt_crumbs"],
    Action.GetVariable,
    [Action.Push, 3],
    [Action.Push, "name"],
    [Action.Push, "forts"],
    [Action.Push, "is_found"],
    [Action.Push, false],
    [Action.Push, "is_required"],
    [Action.Push, true],
    [Action.Push, 3],
    Action.InitObject,
    Action.SetMember,
    [Action.Push, "hunt_crumbs"],
    Action.GetVariable,
    [Action.Push, 4],
    [Action.Push, "name"],
    [Action.Push, "berg"],
    [Action.Push, "is_found"],
    [Action.Push, false],
    [Action.Push, "is_required"],
    [Action.Push, true],
    [Action.Push, 3],
    Action.InitObject,
    Action.SetMember,
    [Action.Push, "hunt_crumbs"],
    Action.GetVariable,
    [Action.Push, 5],
    [Action.Push, "name"],
    [Action.Push, "plaza"],
    [Action.Push, "is_found"],
    [Action.Push, false],
    [Action.Push, "is_required"],
    [Action.Push, true],
    [Action.Push, 3],
    Action.InitObject,
    Action.SetMember,
    [Action.Push, "hunt_crumbs"],
    Action.GetVariable,
    [Action.Push, 6],
    [Action.Push, "name"],
    [Action.Push, "beach"],
    [Action.Push, "is_found"],
    [Action.Push, false],
    [Action.Push, "is_required"],
    [Action.Push, true],
    [Action.Push, 3],
    Action.InitObject,
    Action.SetMember,
    [Action.Push, "hunt_crumbs"],
    Action.GetVariable,
    [Action.Push, 7],
    [Action.Push, "name"],
    [Action.Push, "forest"],
    [Action.Push, "is_found"],
    [Action.Push, false],
    [Action.Push, "is_required"],
    [Action.Push, true],
    [Action.Push, 3],
    Action.InitObject,
    Action.SetMember,
    [Action.Push, "achievement_crumbs"],
    [Action.Push, 0],
    [Action.Push, "Object"],
    Action.NewObject,
    Action.DefineLocal,
    [Action.Push, "achievement_crumbs"],
    Action.GetVariable,
    [Action.Push, 0],
    [Action.Push, "id"],
    [Action.Push, 1],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_01"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 0],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "start_panel"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, 2],
    Action.InitArray,
    Action.SetMember,
    [Action.Push, "achievement_crumbs"],
    Action.GetVariable,
    [Action.Push, 1],
    [Action.Push, "id"],
    [Action.Push, 2],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_03"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 1],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_02"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 0],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_01"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, 3],
    Action.InitArray,
    Action.SetMember,
    [Action.Push, "achievement_crumbs"],
    Action.GetVariable,
    [Action.Push, 2],
    [Action.Push, "id"],
    [Action.Push, 3],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_04"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 2],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_03"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 1],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_02"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 0],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_01"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, 4],
    Action.InitArray,
    Action.SetMember,
    [Action.Push, "achievement_crumbs"],
    Action.GetVariable,
    [Action.Push, 3],
    [Action.Push, "id"],
    [Action.Push, 1],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_02"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 0],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_01"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, 2],
    Action.InitArray,
    Action.SetMember,
    [Action.Push, "achievement_crumbs"],
    Action.GetVariable,
    [Action.Push, 4],
    [Action.Push, "id"],
    [Action.Push, 4],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_05"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 3],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_04"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 2],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_03"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 1],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_02"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 0],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_01"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, 5],
    Action.InitArray,
    Action.SetMember,
    [Action.Push, "achievement_crumbs"],
    Action.GetVariable,
    [Action.Push, 5],
    [Action.Push, "id"],
    [Action.Push, 1],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_02"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 0],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_01"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, 2],
    Action.InitArray,
    Action.SetMember,
    [Action.Push, "achievement_crumbs"],
    Action.GetVariable,
    [Action.Push, 6],
    [Action.Push, "id"],
    [Action.Push, 2],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_03"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 1],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_02"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 0],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_01"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, 3],
    Action.InitArray,
    Action.SetMember,
    [Action.Push, "achievement_crumbs"],
    Action.GetVariable,
    [Action.Push, 7],
    [Action.Push, "id"],
    [Action.Push, 4],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "finish"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 3],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_04"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 2],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_03"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 1],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_02"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 0],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "light_01"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, 5],
    Action.InitArray,
    Action.SetMember,
    [Action.Push, "achievement_crumbs"],
    Action.GetVariable,
    [Action.Push, 8],
    [Action.Push, "id"],
    [Action.Push, 3],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "pad_04"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 2],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "pad_03"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 1],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "pad_02"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 0],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "pad_01"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, 4],
    Action.InitArray,
    Action.SetMember,
    [Action.Push, "achievement_crumbs"],
    Action.GetVariable,
    [Action.Push, 9],
    [Action.Push, "id"],
    [Action.Push, 3],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "pad_04"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 2],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "pad_03"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 1],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "pad_02"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 0],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "pad_01"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, 4],
    Action.InitArray,
    Action.SetMember,
    [Action.Push, "achievement_crumbs"],
    Action.GetVariable,
    [Action.Push, 10],
    [Action.Push, "id"],
    [Action.Push, 3],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "pad_04"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 2],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "pad_03"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 1],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "pad_02"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, "id"],
    [Action.Push, 0],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "pad_01"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, 4],
    Action.InitArray,
    Action.SetMember,
    [Action.Push, "achievement_crumbs"],
    Action.GetVariable,
    [Action.Push, 11],
    [Action.Push, "id"],
    [Action.Push, 0],
    [Action.Push, "active"],
    [Action.Push, false],
    [Action.Push, "name"],
    [Action.Push, "laps"],
    [Action.Push, 3],
    Action.InitObject,
    [Action.Push, 1],
    Action.InitArray,
    Action.SetMember,
    ...getServerCrumbs(),
    ...getStageScript(d.getStageScript()),
    ...getHuntCrumbs(d.getHunt())
  ];

  const bytecode = [...treverseMessages, ...createBytecode(code)];

  return Buffer.from(emitCrumbSwf(new Uint8Array(bytecode)));
}