import { iterateEntries } from "@common/utils";



type HandleLink = HandleName | HandleName[];

/**
 * A map of all the handle extensions in the game.
 * The topmost level begins with the highest level extension, pointing to
 * "directories" (the code before the #), being '' if the code has no #,
 * and then pointing to all the remaining codes, which point to the handles used by it
 */
type HandlerMapping = Record<string, 
  Record<string, HandleLink | Record<string, 
    HandleLink
  >>
>

/** All individual handles. Represent a handle which has a specific extension and argument signature */
export enum Handle {
  SetPosition,
  JoinRoom,
  JoinRoomOld,
  LeaveGame,
  JoinIgloo,
  JoinIglooNew,
  SendAction,
  SendFrame,
  Snowball,
  SendEmote,
  SendCardOld,
  PBI,
  RoomRefresh,
  GetWaddle,
  GetTotalCoins,
  JoinWaddle,
  JoinServerOld,
  GetCoins,
  GetCoins2007,
  GetTableOld,
  JoinTableOld,
  LeaveTableOld,
  GetTableGame,
  JoinTableGame,
  LeaveTableGame,
  SendTableMove,
  AddItemOld,
  UpdatePenguinOld,
  BecomeAgent,
  SendInventory,
  SendMessageOld,
  SetPositionOld,
  SendTeleportOld,
  SendEmoteOld,
  SnowballOld,
  GetInventory2007,
  SetFrameOld,
  GetEpfStatus,
  GetFieldOps,
  GetEpfMedals,
  AddEpfItem,
  BecomeEpfAgent,
  GrantEpfMedals,
  GetPuffleLaunchData,
  SetPuffleLaunchData,
  RollSpyDrills,
  SpyDrillsReward,
  GetIgloo,
  GetIglooTypes,
  GetFurniture,
  AddFurniture,
  UpdateIgloo,
  UpdateIglooMusic,
  AddFlooring,
  AddIgloo,
  UpdateIglooType,
  GetMusicTracks,
  GetIglooLikes,
  GetDj3kTracks,
  GetAllIglooLayouts,
  UpdateIglooNew,
  AddIglooLayout,
  UpdateIglooLayout,
  AddIglooLocation,
  OpenIgloo,
  CloseIgloo,
  GetOpenIgloos,
  OpenIglooOld,
  CloseIglooOld,
  GetOpenIgloosOld,
  GetInventory,
  AddItem,
  UpdateColor,
  UpdateHead,
  UpdateFace,
  UpdateNeck,
  UpdateBody,
  UpdateHand,
  UpdateFeet,
  UpdatePin,
  UpdateBackground,
  JoinServer,
  JoinServerNew,
  GetBuddies,
  GetBuddiesB,
  GetBuddyOnline,
  GetBuddyOnlineB,
  BuddyRequest,
  BuddyRequestB,
  BuddyAccept,
  BuddyAcceptB,
  BuddyDecline,
  BuddyDeclineB,
  BuddyRemove,
  BuddyRemoveB,
  BuddyMessage,
  BuddyMessageB,
  GetPlayerOld,
  GetPlayerOldAlt,
  GN,
  GLR,
  Heartbeat,
  GetIglooInventory,
  GetMail,
  GetAllMail,
  SetMailCheck,
  LeaveWaddle,
  DonateCoins,
  AdoptPuffle,
  AdoptPuffleNew,
  GetIglooPuffles,
  WalkPuffle,
  CheckPuffleName,
  CheckPuffleNameAlt,
  GetPuffleInventory,
  PuffleBackyardSwap,
  PuffleDigRandom,
  PuffleDigOnCommand,
  EatPuffleItem,
  RevealGoldPuffle,
  GetRainbowQuestData,
  SetRainbowQuestTaskComplete,
  RainbowQuestCollectCoins,
  RainbowQuestItemCollect,
  RainbowQuestCollectBonus,
  GetPinInformation,
  GetMissionStamps,
  GetStampbookCoverData,
  GetPlayerStamps,
  GetRecentStamps,
  SetStampbookCoverData,
  SetStampEarned,
  EnterWaddleGame,
  UpdateWaddleGameSeats,
  CardJitsuDeal,
  CardJitsuPick,
  JoinMatchMaking,
  GetNinjaRanks,
  GetNinjaLevel,
  GetCards,
  JoinSled,
  SledRaceAction,
  LeaveWaddleGame,
  HandleSendMessage,
  SendJokeOld,
  SendSafeMessageOld,
  SendSafeMessageOldAlt,
  SendActionOld,
  SendJoke,
  SendSafeMessage,
  JoinSensei,
  JoinTemporaryWaddle,
  LeaveWaddleMatch,
  GetFireLevel,
  CardJitsuFireClickSpinner,
  CardJitsuFireChooseTile,
  CardJitsuFireChooseCard,
  CardJitsuFireInfoReady,
  CardJitsuFireChooseElement,
  EPFStamps,
  OpenBook,
  CloseBook,
  OpenBookOld,
  CloseBookOld,
  JoinIglooOld,
  AddIglooOld,
  GetFurnitureOld,
  AddFurnitureOld,
  UpdateIglooOld,
  GetIgloo2007,
  AddFlooring2007,
  AddIgloo2007,
  GetFurniture2007,
  AddFurniture2007,
  UpdateIgloo2007,
  UpdateIglooMusic2007,
  GetPartyOp,
  SetPartyOp,
  SendLine,
  PlayerTransformation,
  RetrieveMedieval2012,
  Medieval2012ViewedMessage,
  GetBakeryState,
  SendEnterHopper,
  GetCookieInventory,
  CheckNameOld,
  GetHockeyGame,
  MoveHockeyPuck,
  MoveHockeyPuckOld,
  UpdateHockeyGame,
  BuyPowerCards
};

/** Map of all the handles and their valid arguments */
export type HandleArguments = typeof HANDLE_ARGUMENTS;
export const HANDLE_ARGUMENTS = {
  [Handle.SetPosition]: ['number', 'number'],
  [Handle.JoinRoom]: ['number', 'number', 'number'],
  [Handle.JoinRoomOld]: ['number', 'number', 'number'],
  [Handle.LeaveGame]: ['number'],
  [Handle.JoinIgloo]: ['number'],
  [Handle.JoinIglooNew]: ['number', 'string'],
  [Handle.SendAction]: ['string'],
  [Handle.SendFrame]: ['number'],
  [Handle.Snowball]: ['string', 'string'],
  [Handle.SendEmote]: ['string'],
  [Handle.PBI]: ['string'],
  [Handle.RoomRefresh]: [],
  [Handle.GetWaddle]: 'number',
  [Handle.GetTotalCoins]: [],
  [Handle.JoinWaddle]: ['number'],
  [Handle.JoinServerOld]: [],
  [Handle.GetCoins]: [],
  [Handle.GetCoins2007]: [],
  [Handle.GetTableOld]: 'number',
  [Handle.JoinTableOld]: ['number'],
  [Handle.LeaveTableOld]: [],
  [Handle.GetTableGame]: ['number'],
  [Handle.JoinTableGame]: 'number',
  [Handle.LeaveTableGame]: [],
  [Handle.SendTableMove]: 'number',
  [Handle.AddItemOld]: ['number'],
  [Handle.UpdatePenguinOld]: ['number', 'number', 'number', 'number', 'number', 'number', 'number', 'number', 'number'],
  [Handle.BecomeAgent]: [],
  [Handle.SendInventory]: [],
  [Handle.SendMessageOld]: ['string', 'string'],
  [Handle.SetPositionOld]: ['number', 'number'],
  [Handle.SendTeleportOld]: ['number', 'number', 'number'],
  [Handle.SendEmoteOld]: ['string'],
  [Handle.SnowballOld]: ['string', 'string'],
  [Handle.GetInventory2007]: [],
  [Handle.SetFrameOld]: ['number'],
  [Handle.SendCardOld]: ['number', 'number', 'number'],
  [Handle.GetEpfStatus]: [],
  [Handle.GetFieldOps]: [],
  [Handle.GetEpfMedals]: [],
  [Handle.AddEpfItem]: ['number'],
  [Handle.BecomeEpfAgent]: [],
  [Handle.GrantEpfMedals]: ['number'],
  [Handle.GetPuffleLaunchData]: [],
  [Handle.SetPuffleLaunchData]: ['string'],
  [Handle.RollSpyDrills]: [],
  [Handle.SpyDrillsReward]: ['number'],
  [Handle.GetIgloo]: ['number'],
  [Handle.GetIglooTypes]: [],
  [Handle.GetFurniture]: [],
  [Handle.AddFurniture]: ['number'],
  [Handle.UpdateIgloo]: 'string',
  [Handle.UpdateIglooMusic]: ['number'],
  [Handle.AddFlooring]: ['number'],
  [Handle.AddIgloo]: ['number'],
  [Handle.UpdateIglooType]: ['number'],
  [Handle.GetMusicTracks]: [],
  [Handle.GetIglooLikes]: [],
  [Handle.GetDj3kTracks]: [],
  [Handle.GetAllIglooLayouts]: [],
  [Handle.UpdateIglooNew]: ['number', 'number', 'number', 'number', 'number', 'string'],
  [Handle.AddIglooLayout]: [],
  [Handle.UpdateIglooLayout]: ['number'],
  [Handle.AddIglooLocation]: ['number'],
  [Handle.OpenIgloo]: ['string', 'string'],
  [Handle.CloseIgloo]: ['string'],
  [Handle.GetOpenIgloos]: [],
  [Handle.OpenIglooOld]: ['number', 'string'],
  [Handle.CloseIglooOld]: ['number'],
  [Handle.GetOpenIgloosOld]: [],
  [Handle.GetInventory]: [],
  [Handle.AddItem]: ['number'],
  [Handle.UpdateColor]: ['number'],
  [Handle.UpdateHead]: ['number'],
  [Handle.UpdateFace]: ['number'],
  [Handle.UpdateNeck]: ['number'],
  [Handle.UpdateBody]: ['number'],
  [Handle.UpdateHand]: ['number'],
  [Handle.UpdateFeet]: ['number'],
  [Handle.UpdatePin]: ['number'],
  [Handle.UpdateBackground]: ['number'],
  [Handle.JoinServer]: [],
  [Handle.JoinServerNew]: ['number'],
  [Handle.GetBuddies]: [],
  [Handle.GetBuddiesB]: [],
  [Handle.GetBuddyOnline]: [],
  [Handle.GetBuddyOnlineB]: [],
  [Handle.BuddyRequest]: ['number'],
  [Handle.BuddyRequestB]: ['number'],
  [Handle.BuddyAccept]: ['number'],
  [Handle.BuddyAcceptB]: ['number'],
  [Handle.BuddyDecline]: ['number'],
  [Handle.BuddyDeclineB]: ['number'],
  [Handle.BuddyRemove]: ['number'],
  [Handle.BuddyRemoveB]: ['number'],
  [Handle.BuddyMessage]: ['number', 'number'],
  [Handle.BuddyMessageB]: ['number', 'number'],
  [Handle.GetPlayerOld]: ['number'],
  [Handle.GetPlayerOldAlt]: ['number'],
  [Handle.GN]: [],
  [Handle.GLR]: [],
  [Handle.Heartbeat]: [],
  [Handle.GetIglooInventory]: [],
  [Handle.GetMail]: [],
  [Handle.GetAllMail]: [],
  [Handle.SetMailCheck]: [],
  [Handle.LeaveWaddle]: [],
  [Handle.DonateCoins]: ['string', 'number'],
  [Handle.AdoptPuffle]: ['number', 'string'],
  [Handle.AdoptPuffleNew]: ['number', 'string', 'number'],
  [Handle.GetIglooPuffles]: ['number', 'string'],
  [Handle.WalkPuffle]: ['number', 'number'],
  [Handle.CheckPuffleName]: ['string'],
  [Handle.CheckPuffleNameAlt]: ['string'],
  [Handle.GetPuffleInventory]: [],
  [Handle.PuffleBackyardSwap]: ['number', 'string'],
  [Handle.PuffleDigRandom]: [],
  [Handle.PuffleDigOnCommand]: [],
  [Handle.EatPuffleItem]: ['number', 'number'],
  [Handle.RevealGoldPuffle]: [],
  [Handle.GetRainbowQuestData]: [],
  [Handle.SetRainbowQuestTaskComplete]: ['number'],
  [Handle.RainbowQuestCollectCoins]: ['string'],
  [Handle.RainbowQuestItemCollect]: ['number'],
  [Handle.RainbowQuestCollectBonus]: [],
  [Handle.GetPinInformation]: ['string'],
  [Handle.GetMissionStamps]: [],
  [Handle.GetStampbookCoverData]: ['string'],
  [Handle.GetPlayerStamps]: ['string'],
  [Handle.GetRecentStamps]: [],
  [Handle.SetStampbookCoverData]: 'string',
  [Handle.SetStampEarned]: ['number'],
  [Handle.EnterWaddleGame]: [],
  [Handle.UpdateWaddleGameSeats]: [],
  [Handle.CardJitsuDeal]: ['string', 'number'],
  [Handle.CardJitsuPick]: ['string', 'number', 'number'],
  [Handle.JoinMatchMaking]: [],
  [Handle.GetNinjaRanks]: [],
  [Handle.GetNinjaLevel]: [],
  [Handle.GetCards]: [],
  [Handle.JoinSled]: [],
  [Handle.SledRaceAction]: ['string', 'string', 'string', 'string'],
  [Handle.LeaveWaddleGame]: 'number',
  [Handle.HandleSendMessage]: ['string', 'string'],
  [Handle.SendJokeOld]: ['string'],
  [Handle.SendSafeMessageOld]: ['string'],
  [Handle.SendSafeMessageOldAlt]: ['string'],
  [Handle.SendActionOld]: ['string'],
  [Handle.SendJoke]: ['string'],
  [Handle.SendSafeMessage]: ['string'],
  [Handle.JoinSensei]: [],
  [Handle.JoinTemporaryWaddle]: ['number', 'number', 'number'],
  [Handle.LeaveWaddleMatch]: [],
  [Handle.GetFireLevel]: [],
  [Handle.CardJitsuFireClickSpinner]: ['string', 'number', 'number'],
  [Handle.CardJitsuFireChooseTile]: ['string', 'number'],
  [Handle.CardJitsuFireChooseCard]: ['string', 'number'],
  [Handle.CardJitsuFireInfoReady]: ['string'],
  [Handle.CardJitsuFireChooseElement]: ['string', 'string'],
  [Handle.EPFStamps]: ['number'],
  [Handle.OpenBook]: ['number'],
  [Handle.CloseBook]: [],
  [Handle.OpenBookOld]: ['number', 'number'],
  [Handle.CloseBookOld]: [],
  [Handle.JoinIglooOld]: ['number', 'number'],
  [Handle.AddIglooOld]: ['number'],
  [Handle.GetFurnitureOld]: [],
  [Handle.AddFurnitureOld]: ['number'],
  [Handle.UpdateIglooOld]: 'string',
  [Handle.GetIgloo2007]: ['number'],
  [Handle.AddFlooring2007]: ['number'],
  [Handle.AddIgloo2007]: ['number'],
  [Handle.GetFurniture2007]: [],
  [Handle.AddFurniture2007]: ['number'],
  [Handle.UpdateIgloo2007]: 'string',
  [Handle.UpdateIglooMusic2007]: ['number'],
  [Handle.GetPartyOp]: [],
  [Handle.SetPartyOp]: ['number'],
  [Handle.SendLine]: ['number'],
  [Handle.PlayerTransformation]: ['number'],
  [Handle.RetrieveMedieval2012]: ['string'],
  [Handle.Medieval2012ViewedMessage]: ['number'],
  [Handle.GetBakeryState]: [],
  [Handle.SendEnterHopper]: ['string'],
  [Handle.GetCookieInventory]: [],
  [Handle.CheckNameOld]: ['string'],
  [Handle.GetHockeyGame]: [],
  [Handle.MoveHockeyPuck]: ['number', 'number', 'number', 'number', 'number'],
  [Handle.MoveHockeyPuckOld]: ['number', 'number'],
  [Handle.UpdateHockeyGame]: ['number'],
  [Handle.BuyPowerCards]: []
} as const;

const HANDLER_MAPPING: HandlerMapping = {
  's': {
    'jx': Handle.JoinTemporaryWaddle,
    's': {
      'upc': Handle.UpdateColor,
      'uph': Handle.UpdateHead,
      'upf': Handle.UpdateFace,
      'upn': Handle.UpdateNeck,
      'upb': Handle.UpdateBody,
      'upa': Handle.UpdateHand,
      'upe': Handle.UpdateFeet,
      'upl': Handle.UpdatePin,
      'upp': Handle.UpdateBackground
    },
    'ba': {
      'barsu': Handle.GetBakeryState,
      'seh': Handle.SendEnterHopper,
      'ctc': Handle.GetCookieInventory
    },
    'f': {
      'epfga': Handle.GetEpfStatus,
      'epfgf': Handle.GetFieldOps,
      'epfgr': Handle.GetEpfMedals,
      'epfai': Handle.AddEpfItem,
      'epfsa': Handle.BecomeEpfAgent,
      'epfgrantreward': Handle.GrantEpfMedals,
      'epfgp': Handle.GetPartyOp,
      'epfsp': Handle.SetPartyOp
    },
    'g': {
      'go': Handle.GetIglooTypes,
      'gf': Handle.GetFurniture,
      'um': Handle.UpdateIglooMusic,
      'au': Handle.AddIgloo,
      'ao': Handle.UpdateIglooType,
      'gili': Handle.GetIglooLikes,
      'ggd': Handle.GetDj3kTracks,
      'gail': Handle.GetAllIglooLayouts,
      'uic': Handle.UpdateIglooNew,
      'al': Handle.AddIglooLayout,
      'uiss': Handle.UpdateIglooLayout,
      'aloc': Handle.AddIglooLocation,
      'or': Handle.OpenIgloo,
      'cr': Handle.CloseIgloo,
      'gr': Handle.GetOpenIgloos,
      'gii': Handle.GetIglooInventory
    },
    'p': {
      'puffleswap': Handle.PuffleBackyardSwap,
      'puffledig': Handle.PuffleDigRandom,
      'puffledigoncommand': Handle.PuffleDigOnCommand,
      'pcid': Handle.EatPuffleItem,
      'revealgoldpuffle': Handle.RevealGoldPuffle,
      'rpqtc': Handle.SetRainbowQuestTaskComplete
    },
    'l': {
      'mc': Handle.SetMailCheck
    },
    'musictrack': {
      'getmymusictracks': Handle.GetMusicTracks
    },
    'e': {
      'dc': Handle.DonateCoins
    },
    'ni': {
      'gnr': Handle.GetNinjaRanks,
      'gnl': Handle.GetNinjaLevel,
      'gcd': Handle.GetCards,
      'gfl': Handle.GetFireLevel
    },
    'mdvl': {
      'retrieve': Handle.RetrieveMedieval2012,
      'msgviewed': Handle.Medieval2012ViewedMessage
    },
    'cd': {
      'bpc': Handle.BuyPowerCards
    }
  },
  'z': {
    'zo': [Handle.LeaveWaddleGame],
    'gw': Handle.GetWaddle,
    'jw': Handle.JoinWaddle,
    'ggd': Handle.GetPuffleLaunchData,
    'sgd': Handle.SetPuffleLaunchData,
    'zr': Handle.RollSpyDrills,
    'zc': Handle.SpyDrillsReward,
    'lw': Handle.LeaveWaddle,
    'gz': [Handle.EnterWaddleGame, Handle.GetTableGame, Handle.GetHockeyGame],
    'uz': [Handle.UpdateWaddleGameSeats, Handle.UpdateHockeyGame],
    'zm': [
      Handle.SledRaceAction,
      Handle.CardJitsuDeal,
      Handle.CardJitsuPick,
      Handle.CardJitsuFireClickSpinner,
      Handle.CardJitsuFireChooseTile,
      Handle.CardJitsuFireChooseCard,
      Handle.CardJitsuFireInfoReady,
      Handle.CardJitsuFireChooseElement,
      Handle.SendTableMove,
      Handle.MoveHockeyPuckOld
    ],
    'jmm': Handle.JoinMatchMaking,
    'jz': [Handle.JoinSled, Handle.JoinTableGame],
    'jsen': Handle.JoinSensei,
    'lz': [Handle.LeaveWaddleMatch, Handle.LeaveTableGame],
    'epfsf': Handle.EPFStamps,
    'm': Handle.MoveHockeyPuck
  }
}

type XtName = {
  extension: string;
  code: string;
}


export const handlePacketNames = new Map<HandleName, XtName>();

function iterateHandles(ext: string, code: string, handles: Handle | Handle[], dir?: string) {
  let array = typeof handles === 'number' ? [handles] : handles;
  array.forEach(handle => {
    handlePacketNames.set(handle, { extension: ext, code: dir === undefined ? code : `${dir}#${code}` });
  });
}

iterateEntries(HANDLER_MAPPING, (ext, dirs) => {
  iterateEntries(dirs, (dir, codes) => {
    if (typeof codes === 'number' || Array.isArray(codes)) {
      iterateHandles(ext, dir, codes);
    } else {
      iterateEntries(codes, (code, names) => {
        // "root handler"
        if (code === '') {
          iterateHandles(ext, dir, names);
        } else {
          iterateHandles(ext, code, names, dir);
        }
      })
    }
  });
});

export type HandleName = keyof typeof HANDLE_ARGUMENTS;

