export const ERROR_LANG: Record<string, string> = {
  KICK: "A moderator has removed you from this server. Please be careful what you say and do online and remember to follow the Club Penguin rules.",
  MODERATOR_BAN: "A moderator has banned your account. Your ban will expire in: %number% hours",
  GAME_CHEAT: "The system has automatically removed you from the server. Please be careful what you say and do online and remember to follow the Club Penguin rules.",
  AUTO_BAN: "<b>Banned:</b>\nThe server has automatically banned you for saying a bad word.\nYou Said: \"%badword%\"",
  BAN_DURATION: "<b>Banned:</b>\nYou are banned for the next %0 %1",
  BAN_FOREVER: "<b>Banned:</b>\nYou are banned forever",
  BAN_AN_HOUR: "<b>Banned:</b>\nYour ban will expire within the hour",
  HACKING_AUTO_BAN: "<b>Banned:<\b>\nThe server has automatically banned you.\nReason: \"%reason%\"",
  BUDDY_LIMIT: "Sorry, you may only have %number% buddies. Please remove some buddies to add more",
  TIME_WARNING: "You have %number% minutes remaining on the Club Penguin Timer. Have fun!",
  NO_PLAY_TIME: "Time's up. Thanks for playing! Check out the <b>%0Community%1</b> section of the website for fun ways to spend your time outside of Club Penguin.",
  PLAY_TIME_OVER: "Time's up. Thanks for playing! Check out the <b>%0Community%1</b> section of the website for fun ways to spend your time outside of Club Penguin.",
  OUT_PLAY_TIME: "You can only play between the hours of %0 and %1.",
  GROUNDED: "You cannot play because you're currently grounded.",
  PLAYER_IN_ROOM: "Please exit your game before leaving the room",
  DEFAULT_ERROR: "There was an error",
  TIME_OUT: "Auto Disconnect, your penguin has been idle for more than 10 minutes",
  CONNECTION_LOST: "Connection was lost.\nPlease click to learn more",
  LOAD_ERROR: "<b>Load Error</b>\nPlease clear your cache and try again",
  MULTI_CONNECTIONS: "You can only have one Club Penguin window open at a time. Please close any other windows and tabs in your internet browser to connect.",
  ACCOUNT_NOT_ACTIVATE: "Your account has not been activated",
  NO_CONNECTION: "Having trouble connecting? Please try again, or contact support if the problem continues.",
  ITEM_NOT_EXIST: "This item is not currently available.",
  CONNECTION_TIMEOUT: "Connection timeout. Please choose another server or try again later.",
  MAX_IGLOO_FURNITURE_ERROR: "Sorry, your igloo may only contain %number% items. Please remove an item to add this item.",
  NOT_MEMBER: "Oops! You need to purchase a membership to buy %type%. We would love to have you join. Click the button below to see more about membership",
  PASSWORD_REQUIRED: "You must provide your password \nto enter Club Penguin",
  PASSWORD_SHORT: "Your password is too short. \nPlease try again",
  PASSWORD_LONG: "Your password is too long. \nPlease try again",
  PASSWORD_WRONG: "Incorrect Password. \nNOTE: Passwords are CaSe SeNsiTIVE",
  PUFFLE_LIMIT_M: "Sorry, you may only have a maximum of %number% puffles",
  PUFFLE_LIMIT_NM: "Sorry, you must be a member to have more than %number% puffles",
  NAME_NOT_ALLOWED: "Sorry, this name is not available. Please try again",
  REDEMPTION_CONNECTION_LOST: "Lost connection. If you have not clicked \"Done\", you can reuse this code at another time.",
  REDEMPTION_ALREADY_HAVE_ITEM: "You already have this item.",
  REDEMPTION_SERVER_FULL: "The server is full. Please try again later.",
  REDEMPTION_BOOK_ID_NOT_EXIST: "That book does not exist.",
  REDEMPTION_BOOK_ALREADY_REDEEMED: "You have already unlocked this book.",
  REDEMPTION_WRONG_BOOK_ANSWER: "You have entered an incorrect answer.",
  REDEMPTION_BOOK_TOO_MANY_ATTEMPTS: "An incorrect answer has been entered 5 times. Please try again later.",
  REDEMPTION_CODE_NOT_FOUND: "The code you have entered is incorrect.",
  REDEMPTION_CODE_ALREADY_REDEEMED: "The code you entered has already been used.",
  REDEMPTION_TOO_MANY_ATTEMPTS: "An incorrect code has been entered 5 times. Please try again in\n45 minutes.",
  REDEMPTION_CATALOG_NOT_AVAILABLE: "Sorry, the catalog you're looking for is not available yet. Please try again at a later date.",
  REDEMPTION_PUFFLES_MAX: "You already have the maximum number of puffles.",
  REDEMPTION_PUFFLE_INVALID: "Please choose a different puffle name.",
  REDEMPTION_PUFFLE_CODE_MAX: "You can only redeem one puffle per code.",
  REDEMPTION_CODE_TOO_SHORT: "The code is too short.\nIt must be at least 9 characters.",
  REDEMPTION_CODE_TOO_LONG: "The code is too long.\nIt must be 16 characters or shorter.",
  REDEMPTION_NO_EXCLUSIVE_REDEEMS: "You've chosen all of your Super Exclusive bonus items.",
  REDEMPTION_CODE_GROUP_REDEEMED: "Only one code containing 2500 coins can be redeemed per account.",
  REDEMPTION_CODE_EXPIRED: "The code you have entered has expired",
  GOLDEN_CODE_NOT_READY: "You'll be able to redeem this code Nov. 25. Please come back then...",
  ITEM_IN_HOUSE: "You already have this item",
  NOT_ENOUGH_COINS: "You need more coins",
  NOT_ENOUGH_MEDALS: "You don't have enough medals to obtain this item.",
  NAME_REQUIRED: "You must provide your Penguin Name to enter Club Penguin",
  NAME_SHORT: "Your Penguin Name is too short. Please try again",
  NAME_LONG: "Your Penguin Name is too long. Please try again",
  NAME_NOT_FOUND: "Penguin not found. Try Again?",
  LOGIN_FAILED: "Login Failed, please try at a later time",
  LOGIN_FLOODING_DAILY: "Maximum login attempts exceeded. Please try again in an hour",
  LOGIN_FLOODING: "Maximum login attempts exceeded. Please try again in an hour",
  PASSWORD_SAVE_PROMPT: "Do not use this feature if\nyou are using a school, library,\nor public computer.\n\nAnyone that uses this computer will have access to your penguin.",
  SERVER_FULL: "Sorry this server is full. Please select another server.",
  ROOM_FULL: "Sorry this room is currently full",
  GAME_FULL: "Sorry, this game is full. Check back in a little while. Thank you for your patience!",
  MAX_STAMPBOOK_COVER_ITEMS: "Only %number% items can be stuck on the cover at once."
}