export const LANG: Record<string, string> = {
  aqua_find: "%name% is playing Aqua Grabber",
  astro_find: "%name% is playing Astro Barrier",
  beans_find: "%name% is playing Bean Counters",
  cart_find: "%name% is Cart Surfing",
  fish_find: "%name% is Ice Fishing",
  jetpack_find: "%name% is flying a Jet Pack",
  thinice_find: "%name% is playing Thin Ice",
  waves_find: "%name% is Surfing",
  hydro_find: "%name% is playing Hydro Hopper",
  pizzatron_find: "%name% is making pizzas",
  roundup_find: "%name% is rounding up puffles",
  mancala_find: "%name% is playing Manacala",
  four_find: "%name% is playing Find Four",
  sled_find: "%name% is in a Sled Race",
  book1_find: "%name% is reading a Book",
  book2_find: "%name% is reading a Book",
  book3_find: "%name% is reading a Book",
  mixmaster_find: "%name% is Mixing Music",
  treasurehunt_find: "%name% is digging for treasure",
  balloon_find: "%name% is playing Balloon Pop",
  bell_find: "%name% is playing Ring The Bell",
  feed_find: "%name% is playing Feed-A-Puffle",
  memory_find: "%name% is playing Memory Card Game",
  paddle_find: "%name% is playing Puffle Paddle",
  shuffle_find: "%name% is playing Puffle Shuffle",
  soaker_find: "%name% is playing Puffle Soaker",
  spin_find: "%name% is playing Grab & Spin",
  card_find: "%name% is playing Card-Jitsu",
  fire_find: "%name% is playing Card-Jitsu Fire",
  water_find: "%name% is playing Card-Jitsu Water",
  sensei_find: "%name% is challenging the Sensei",
  firesensei_find: "%name% is challenging the Sensei",
  watersensei_find: "%name% is challenging the Sensei",
  dancing_find: "%name% is in a Dance Contest!",
  rescue_find: "%name% is Rescuing Puffles",
  systemdefend_find: "%name% is playing System Defender",
  mission1_find: "%name% is on an Adventure",
  mission2_find: "%name% is on an Adventure",
  mission3_find: "%name% is on an Adventure",
  mission4_find: "%name% is on an Adventure",
  mission5_find: "%name% is on an Adventure",
  mission6_find: "%name% is on an Adventure",
  mission7_find: "%name% is on an Adventure",
  mission8_find: "%name% is on an Adventure",
  mission9_find: "%name% is on an Adventure",
  mission10_find: "%name% is on an Adventure",
  mission11_find: "%name% is on an Adventure",
  town_find: "%name% is in the Town",
  coffee_find: "%name% is in the Coffee Shop",
  book_find: "%name% is in the Book Room",
  dance_find: "%name% is in the Dance Club",
  lounge_find: "%name% is in the Dance Lounge",
  shop_find: "%name% is in the Gift Shop",
  village_find: "%name% is in the Ski Village",
  lodge_find: "%name% is in the Ski Lodge",
  attic_find: "%name% is in the Lodge Attic",
  mtn_find: "%name% is on top of the Mountain",
  sport_find: "%name% is in the Sport Shop",
  plaza_find: "%name% is in the Plaza",
  pet_find: "%name% is in the Pet Shop",
  dojo_find: "%name% is in the Dojo",
  dojoext_find: "%name% is in the Dojo Courtyard",
  dojohide_find: "%name% is in Hiding",
  dojofire_find: "%name% is in Hiding",
  dojowater_find: "%name% is in the Water Dojo",
  pizza_find: "%name% is in the Pizza Parlor",
  stage_find: "%name% is at the Stage",
  beach_find: "%name% is at the Beach",
  light_find: "%name% is in the Lighthouse",
  beacon_find: "%name% is at the Lighthouse Beacon",
  ship_find: "%name% is on the Pirate Ship",
  shiphold_find: "%name% is in the Pirate Ship Hold",
  shipquarters_find: "%name% is in the Captain\'s Quarterss",
  shipnest_find: "%name% is in the Crow\'s Nest",
  dock_find: "%name% is at the Dock",
  forts_find: "%name% is at the Snow Forts",
  rink_find: "%name% is at the Stadium",
  agent_find: "%name% is hiding",
  agentcom_find: "%name% is hiding",
  agentlobbysolo_find: "%name% is hiding",
  agentlobbymulti_find: "%name% is in the Everyday Phoning Facility",
  agentvr_find: "%name% is hiding",
  boiler_find: "%name% is in the Boiler Room",
  berg_find: "%name% is on the Iceberg (hidden on your map)",
  cave_find: "%name% is in the Cave (hidden underground)",
  mine_find: "%name% is in the Mine (hidden underground)",
  shack_find: "%name% is in the Mine Shack (hidden on your map)",
  forest_find: "%name% is in the Forest",
  cove_find: "%name% is at the Cove",
  boxdimension_find: "%name% is in the Box Dimension",
  cavemine_find: "%name% is at the Cave Mine",
  lake_find: "%name% is at the Hidden Lake",
  underwater_find: "%name% is in the Underwater Room",
  eco_find: "%name% is in the Recycling Plant",
  party_find: "%name% is on the Sleigh",
  party1_find: "%name% is at the Hoedown",
  party2_find: "%name% is inside the Haunted House",
  party3_find: "%name% is in the Dark Swamp",
  party4_find: "%name% is in the Dark Chamber",
  party5_find: "%name% is in the Monster Room",
  party6_find: "%name% is in a cave",
  party7_find: "%name% is in the Maze",
  party8_find: "%name% is in the Maze",
  party9_find: "%name% is in the Maze",
  party10_find: "%name% is in the Maze",
  party11_find: "%name% is in the Maze",
  party12_find: "%name% is at the end of the Maze",
  party13_find: "%name% is beneath the Volcano",
  party14_find: "%name% is beneath the Volcano",
  party15_find: "%name% is beneath the Volcano",
  party16_find: "%name% is beneath the Volcano",
  party17_find: "%name% is beneath the Volcano",
  party18_find: "%name% is in the Treasure Room",
  party99_find: "%name% is ???",
  igloo_find: "%name% is in an igloo",
  igloo_theirs_find: "%name% is in their igloo",
  igloo_yours_find: "%name% is in your igloo",
  ignore_request_prompt: "Would you like to add %name% to your ignore list?",
  ignore_request_sent_prompt: "Done",
  ignore_remove_prompt: "Would you like to remove %name% from your ignore list?",
  remove_done_prompt: "Done",
  town: "Town",
  coffee: "Coffee Shop",
  book: "Book Room",
  dance: "Dance Club",
  lounge: "Dance Lounge",
  shop: "Gift Shop",
  village: "Ski Village",
  lodge: "Ski Lodge",
  attic: "Lodge Attic",
  sport: "Sport Shop",
  mtn: "Mountain",
  plaza: "Plaza",
  pet: "Pet Shop",
  dojo: "Dojo",
  dojoext: "Dojo Courtyard",
  dojohide: "Ninja Hideout",
  dojofire: "Fire Dojo",
  dojowater: "Water Dojo",
  pizza: "Pizza Parlor",
  stage: "Stage",
  beach: "Beach",
  light: "Lighthouse",
  beacon: "Beacon",
  ship: "Pirate Ship",
  shiphold: "Ship Hold",
  shipquarters: "Captain\'s Quarters",
  shipnest: "Crow\'s Nest",
  dock: "Dock",
  forts: "Snow Forts",
  rink: "Stadium",
  agent: "HQ",
  agentcom: "EPF Command Room",
  agentlobbysolo: "The Facility",
  agentlobbymulti: "Everyday Phoning Facility",
  agentvr: "VR Room",
  boiler: "Boiler Room",
  berg: "Iceberg",
  cave: "Cave",
  mine: "Mine",
  shack: "Mine Shack",
  forest: "Forest",
  cove: "Cove",
  boxdimension: "Box Dimension",
  cavemine: "Cave Mine",
  lake: "Hidden Lake",
  underwater: "Underwater Room",
  eco: "Recycling Plant",
  party: "Sleigh",
  party1: "House Entrance",
  party2: "Haunted House",
  party3: "Dark Swamp",
  party4: "Dark Chamber",
  party5: "Monster Room",
  party6: "Cave",
  party7: "Maze",
  party8: "Maze",
  party9: "Maze",
  party10: "Maze",
  party11: "Maze Finish",
  party12: "Beneath Volcano",
  party13: "Beneath Volcano",
  party14: "Beneath Volcano",
  party15: "Beneath Volcano",
  party16: "Beneath Volcano",
  party17: "Beneath Volcano",
  party18: "Treasure Room",
  party99: "???",
  buddy_online: "%name% is online",
  buddy_request_prompt: "Would you like to add %name%\nto your buddy list?",
  buddy_request_sent_prompt: "Request Sent",
  buddy_remove_prompt: "Would you like to remove %name% from your buddy list?",
  buddy_question_prompt: "%name% has asked to be your buddy. Do you accept?",
  buddy_accepted_prompt: "%name% is now your buddy!",
  "Loading Create Penguin": "Loading Create Penguin",
  "Loading Content": "Loading Content",
  "Loading Engine": "Loading Engine",
  "Loading Interface": "Loading Interface",
  "Loading Gridview": "Loading Gridview",
  "Loading Mail": "Loading Mail",
  "Loading Clothing": "Loading Clothing",
  "Loading Your Inventory": "Loading Your Inventory",
  "Loading Local Language": "Loading Local Language",
  load_igloo: "Loading the Igloo",
  unlock_igloo_prompt: "Would you like to open your igloo?\nThis will add your igloo to the map.",
  energy: "Energy",
  health: "Health",
  rest: "Rest",
  play_puffle_hint: "Play with Pet",
  feed_puffle_hint: "Feed your Pet",
  rest_puffle_hint: "Sleep",
  walk_puffle_hint: "Walk your Pet",
  "Loading Your Furniture": "Loading Your Furniture",
  "Stop Edit": "Stop Edit",
  "Edit Igloo": "Edit Igloo",
  "Loading Controls": "Loading Controls",
  "Loading Furniture": "Loading Furniture",
  "Loading Floor": "Loading Floor",
  "Lock Igloo": "Close Igloo",
  "Unlock Igloo": "Open Igloo",
  "View Items": "View Items",
  "Buy Items": "Buy Items",
  "Upgrade Igloo": "Upgrade Igloo",
  "Play Music": "Play Music",
  "Save Igloo": "Save Igloo",
  All: "All",
  "Enter Contest": "Enter Contest",
  "View Stored Igloo": "View Stored Igloo",
  buddy_list: "Your Friends",
  online_list: "Users in Room",
  ignore_list: "Ignore List",
  archives_hint: "Old news",
  aqua_hint: "Aqua Grabber",
  astro_hint: "Astro Barrier",
  beans_hint: "Play Beans",
  cart_hint: "Cart Surfer",
  fish_hint: "Go Fishing",
  jetpack_hint: "Play Jet Pack",
  thinice_hint: "Thin Ice",
  waves_hint: "Go Surfing",
  hydro_hint: "Hydro Hopper",
  pizzatron_hint: "Play Pizzatron",
  roundup_hint: "Puffle Roundup",
  mancala_hint: "Play Mancala",
  four_hint: "Play Find Four",
  sled_hint: "Join Sled Race",
  mixmaster_hint: "Mix Music",
  treasurehunt_hint: "Treasure Hunt",
  balloon_hint: "Balloon Pop",
  bell_hint: "Ring The Bell",
  feed_hint: "Feed-A-Puffle",
  memory_hint: "Memory Game",
  paddle_hint: "Puffle Paddle",
  shuffle_hint: "Puffle Shuffle",
  soaker_hint: "Puffle Soaker",
  spin_hint: "Grab & Spin",
  card_hint: "Practice Card-Jitsu",
  fire_hint: "Practice Card-Jitsu Fire",
  water_hint: "Practice Card-Jitsu Water",
  dancing_hint: "Dance Contest",
  rescue_hint: "Puffle Rescue",
  systemdefend_hint: "System Defender",
  profile_hint: "Find Player",
  send_mail_hint: "Send Mail",
  free_item_hint: "Free Gift",
  report_player_hint: "Report Player",
  add_ignore_hint: "Ignore Player",
  remove_ignore_hint: "Remove Ignore",
  add_buddy_hint: "Add Buddy",
  remove_buddy_hint: "Remove Buddy",
  visit_home_hint: "Visit Igloo",
  ban_player_hint: "Ban Player",
  mute_player_hint: "Mute Player",
  kick_player_hint: "Kick Player",
  remove_hint: "Clear Penguin",
  town_hint: "Town",
  coffee_hint: "Coffee Shop",
  book_hint: "Book Room",
  dance_hint: "Dance Club",
  lounge_hint: "Lounge",
  shop_hint: "Gift Shop",
  village_hint: "Ski Village",
  sport_hint: "Sport Shop",
  lodge_hint: "Ski Lodge",
  attic_hint: "Lodge Attic",
  mtn_hint: "Ski Hill",
  plaza_hint: "The Plaza",
  pet_hint: "Pet Shop",
  dojo_hint: "Dojo",
  dojoext_hint: "Dojo Courtyard",
  dojowater_hint: "Water Dojo",
  pizza_hint: "Pizza Parlor",
  stage_hint: "Stage",
  beach_hint: "The Beach",
  light_hint: "Lighthouse",
  beacon_hint: "Beacon",
  ship_hint: "Pirate Ship",
  shiphold_hint: "Hold",
  shipquarters_hint: "Captain\'s Quarters",
  shipnest_hint: "Crow\'s Nest",
  dock_hint: "The Dock",
  forts_hint: "Snow Forts",
  rink_hint: "Stadium",
  agentcom_hint: "EPF Command Room",
  agentlobbysolo_hint: "Facility",
  agentlobbymulti_hint: "Everyday Phoning Facility",
  agentvr_hint: "VR Room",
  boiler_hint: "Boiler Room",
  berg_hint: "Iceberg",
  cave_hint: "Cave",
  mine_hint: "Mine",
  shack_hint: "Mine Shack",
  forest_hint: "Forest",
  cove_hint: "Cove",
  boxdimension_hint: "Box Dimension",
  cavemine_hint: "Cave Mine",
  lake_hint: "Hidden Lake",
  underwater_hint: "Underwater Room",
  eco_hint: "Recycling Plant",
  party_hint: "Sleigh",
  party1_hint: "Hoedown",
  party2_hint: "Haunted House",
  party3_hint: "Dark Swamp",
  party4_hint: "Dark Chamber",
  party5_hint: "Monster Room",
  party6_hint: "Cave",
  party7_hint: "Maze",
  party8_hint: "Maze",
  party9_hint: "Maze",
  party10_hint: "Maze",
  party11_hint: "Maze Finish",
  party12_hint: "Beneath the Volcano",
  party13_hint: "Beneath the Volcano",
  party14_hint: "Beneath the Volcano",
  party15_hint: "Beneath the Volcano",
  party16_hint: "Beneath the Volcano",
  party17_hint: "Beneath the Volcano",
  party18_hint: "Treasure Room",
  party99_hint: "???",
  igloos_hint: "Member Igloos",
  all_items: "All Items",
  head_items: "Head Items",
  face_items: "Face Items",
  neck_items: "Neck Items",
  body_items: "Body Items",
  hand_items: "Hand Items",
  feet_items: "Feet Items",
  flag_items: "Pins/Flags",
  other_items: "Other Items",
  photo_items: "Backgrounds",
  award_items: "Awards",
  colour_items: "Colors",
  teleport: "Teleport",
  visit_hq: "Visit HQ",
  emote_hint: "Emotes",
  action_hint: "Actions",
  throw_hint: "Snowball",
  buddy_hint: "Show Buddies",
  online_hint: "Show Online",
  ignore_hint: "Show Ignored",
  player_hint: "Edit Player",
  home_hint: "Your Home",
  help_hint: "Edit Account",
  send_hint: "Send",
  safe_hint: "Messages",
  "Incorrect Password": "Incorrect Password",
  "Too many failed login attempts. Please try again later.": "Too many failed login attempts. Please try again later.",
  Joining: "Joining",
  "Logging in": "Logging in",
  "Joining Players Igloo": "Joining Player\'s Igloo",
  "Please Select a Server": "PLEASE SELECT A SERVER",
  "Penguin Name:": "Penguin Name:",
  "Password:": "Password:",
  "Remember me on this computer": "Remember me on this computer",
  "Remember my password": "Remember my password",
  "Forgot your password?": "Forgot your password?",
  "Forget my penguin": "Forget my penguin",
  "Login as a different penguin": "Login as a different penguin",
  "Your Suggested Servers": "Your Suggested Servers",
  "Buddies online": "Buddies online",
  "Amount of penguins online": "Amount of penguins online",
  "Ultimate safe chat": "Ultimate safe chat",
  Parents: "Parents",
  "Click Here": "Click Here",
  "Don\'t have a penguin?": "Don\'t have a penguin?",
  "Create a free account now": "Create a free account now",
  Play: "Start",
  Back: "Back",
  remove_all_mail_prompt: "This will permanently remove all postcards from %nickname%. Do you want to do this?",
  remove_single_mail_prompt: "Are you sure you want to recycle this postcard from %nickname%?",
  "Are you sure you want to ignore %playername%?": "Are you sure you want to ignore %playername%?",
  "This will remove all messages from %playername%. This is not undoable.": "This will remove all messages from %playername%. This is not undoable.",
  "You have %number% postcards!": "You have %number% postcards!",
  "You have 1 postcard!": "You have 1 postcard!",
  "You have no postcards!": "You have no postcards!",
  "From:": "From:",
  "New!": "New!",
  message: "message",
  "Send this postcard to %0 for %1 coins?": "Send this postcard to %0 for %1 coins?",
  "Buy and send postcards for": "Buy and send\npostcards for",
  "Send to:": "Send to:",
  "Failed to send Postcard. You need more coins.": "Failed to send Postcard.\nYou need more coins.",
  "This penguins mailbox is full. Your postcard could not be sent. Please try again later.": "This penguin\'s mailbox is full. Your postcard could not be sent. Please try again later.",
  "Postcard sent": "Postcard sent",
  Postcards: "Postcards",
  "Preview Postcard": "Preview Postcard",
  "Select a Postcard": "Select a Postcard",
  "Send to": "Send To",
  Inbox: "Inbox",
  "You have no postcards": "You have no postcards",
  aqua_prompt: "Would you like to play\nAqua Grabber?",
  astro_prompt: "Would you like to play\nAstro Barrier?",
  beans_prompt: "Would you like to play\nBean Counters?",
  jetpack_prompt: "Would you like to go on a\nJet Pack Adventure?",
  fish_prompt: "Would you like to go\nIce Fishing?",
  hydro_prompt: "Would you like to play\nHydro Hopper?",
  roundup_prompt: "Would you like to play\nPuffle Roundup?",
  mancala_prompt: "Would you like to join this\nMancala game?",
  four_prompt: "Would you like to join this\nFind Four game?",
  cart_prompt: "Would you like to go\nCart Surfing?",
  thinice_prompt: "Would you like to play\nThin Ice?",
  pizzatron_prompt: "Would you like to play\nPizzatron 3000?",
  waves_prompt: "Would you like to\ncatch some waves?",
  sled_prompt: "Would you like to join this\nSled race?",
  book1_prompt: "Would you like to read\nMy Puffle?",
  book2_prompt: "Would you like to read\nBurnt Out Bulbs?",
  book3_prompt: "Would you like to read\nLime Green Dojo Clean?",
  mixmaster_prompt: "Would you like to play\nDJ3K?",
  treasurehunt_prompt: "Would you like to \ndig for treasure?",
  balloon_prompt: "Would you like to play\nBalloon Pop?",
  bell_prompt: "Would you like to play\nRing The Bell?",
  feed_prompt: "Would you like to play\nFeed-A-Puffle?",
  memory_prompt: "Would you like to play\nMemory Card Game?",
  paddle_prompt: "Would you like to play\nPuffle Paddle?",
  shuffle_prompt: "Would you like to play\nPuffle Shuffle?",
  soaker_prompt: "Would you like to play\nPuffle Soaker?",
  spin_prompt: "Would you like to play\nGrab & Spin?",
  card_prompt: "Would you like to practice\nCard-Jitsu?",
  fire_prompt: "Would you like to practice\nCard-Jitsu Fire?",
  water_prompt: "Would you like to practice\nCard-Jitsu Water?",
  sensei_prompt: "Would you like to talk\nto the Sensei?",
  firesensei_prompt: "Would you like to talk\nto the Sensei?",
  watersensei_prompt: "Would you like to talk\nto the Sensei?",
  starter_deck_prompt: "You need a deck of Cards to play.\nPlease see the Sensei first.",
  fire_deck_prompt: "You need a Fire Booster Deck to play.\nPlease see the Sensei first.",
  water_deck_prompt: "You need a Water Booster Deck to play.\nPlease see the Sensei first.",
  dancing_prompt: "Would you like to dance?",
  rescue_prompt: "Would you like to play Puffle Rescue?",
  systemdefend_prompt: "Would you like to play System Defender?",
  game_over0: "You have earned 0 coins.\nYou now have %total% coins.",
  game_over1: "You have earned 1 coin.\nYou now have %total% coins.",
  game_over2: "You have earned %num% coins.\nYou now have %total% coins.",
  quit_game_prompt: "Are you sure you want to quit this game?",
  player_quit_prompt: "%name% has quit the game.",
  tutorial_prompts: "Loading Tutorial Prompt",
  widget_coins: "Your Coins: %total%",
  coins: "coins",
  adopt_puffle: "Would you like to adopt this puffle for 800 coins?",
  name_puffle: "Your puffle needs a name.",
  adopt_puffle_done: "Your new puffle is now in your igloo. Enjoy!",
  max_puffles_prompt: "Sorry, you may only have a\nmaximum of 19 puffles",
  igloo_upgrade_warn: "WARNING\nThis upgrade will replace your current igloo. All your furniture will be moved to storage. Any floor upgrades will be lost.",
  buy_inventory: "Would you like to buy %name% for %cost% coins.",
  buy_furniture: "Would you like to buy %name% for %cost% coins.",
  buy_igloo_upgrade: "Would you like to buy %name% for %cost% coins.",
  buy_igloo_floor: "Would you like to buy %name% for %cost% coins.",
  buy_puffle_food: "Would you like to buy some Pet Food for 10 coins?",
  buy_puffle_bath: "Would you like to bathe your puffle for 5 coins?",
  buy_puffle_gum: "Would you like to buy some Gum for 5 coins?",
  buy_puffle_cookie: "Would you like to buy a Cookie for 5 coins?",
  buy_inventory_done: "%name%\nhas been added to your inventory.",
  buy_furniture_done: "%name%\nhas been added to your inventory.",
  num_coins: "You currently have %num% coins.",
  inventory_free: "You have found a %name%.\nWould you like to pick it up?",
  inventory_medal: "Would you like to get your Medal of Excellence?",
  inventory_gift: "Would you like to get your gift?",
  furniture_free: "You have found a %name%.\nWould you like to pick it up?",
  igloo_upgrade_free: "You have found a %name%.\nWould you like to upgrade your igloo?",
  item_in_inventory_warn: "You already have this item.",
  tour_guide_hat_required: "Sorry, you must wear the tour guide\nhat to use this feature",
  igloo_activate_warn: "Are you sure you want to change your igloo? Your flooring will be lost. Igloo items will be saved in your inventory.",
  low_coin_warn: "You need more coins.",
  duplicate_igloo_warn: "You already have this igloo.",
  duplicate_floor_warn: "You already have this flooring.",
  White_belt: "White",
  Yellow_belt: "Yellow",
  Orange_belt: "Orange",
  Green_belt: "Green",
  Blue_belt: "Blue",
  Red_belt: "Red",
  Purple_belt: "Purple",
  Brown_belt: "Brown",
  Black_belt: "Black",
  Blue: "Blue",
  Pink: "Pink",
  Black: "Black",
  Green: "Green",
  Purple: "Purple",
  Red: "Red",
  Yellow: "Yellow",
  White: "White",
  Orange: "Orange",
  Brown: "Brown",
  "Login to Unlock Your Items": "Login to Unlock Your Items",
  "What word is on page %0, %1 %2 from the left on line %3?": "What word is on page %0, %1 %2 from the left on line %3?",
  word: "word",
  words: "words",
  "items remaining": "items remaining",
  "item remaining": "item remaining",
  "You have unlocked %number% item(s)!": "You have unlocked %number% item(s)!",
  "You still have items to unlock. Your code is only valid once, if you quit before you finish unlocking all your items your remaining choices will be lost. Are you sure you want to quit?": "You still have items to unlock. Your code is only valid once, if you quit before you finish unlocking all your items your remaining choices will be lost.\nAre you sure you want to quit?",
  "Are you sure you want to redeem %itemName%?": "Are you sure you want to redeem\n %itemName%?",
  Hello: "Hello",
  "Congratulations! Youre done! Click Yes to see what has been added to your inventory.": "Congratulations! You\'re done! Click Yes to see what has been added to your inventory.",
  "You\'ll need to enter %number% more Treasure Book code(s) to unlock this page.": "You\'ll need to enter %number% more Treasure Book code(s) to unlock this page.",
  Puffle: "Puffle",
  Blue_puffle: "Blue",
  Pink_puffle: "Pink",
  Black_puffle: "Black",
  Green_puffle: "Green",
  Purple_puffle: "Purple",
  Red_puffle: "Red",
  Yellow_puffle: "Yellow",
  White_puffle: "White",
  Orange_puffle: "Orange",
  Brown_puffle: "Brown",
  golden_code_elemental_reward_title: "You now have the %item%!",
  "You\'ll need to enter %number% more code(s) to unlock this page.": "You\'ll need to enter %number% more code(s) to unlock this page.",
  "You can choose %number% more Super Exclusive item(s).": "You can choose %number% more Super Exclusive item(s).",
  Yes: "Yes",
  No: "No",
  Ok: "Ok",
  Start: "Start",
  Okay: "Okay",
  Close: "Close",
  Continue: "Continue",
  "Learn More": "Learn More",
  Login: "Login",
  "Sign In": "Sign In",
  "Visit Community Section": "Visit Community Section",
  chat_restrict: "a-z A-Z !? 0-9 .,,:`´-_/\\(){}=&$§\"=?@\'*+-ßäöüÄÖÜ#?<>\n\t",
  "Loading Localized Files": "Loading Localized Files",
  "Loading Global Files": "Loading Global Files",
  "Loading Communication": "Loading Communication",
  "Loading Login Screen": "Loading Login",
  "Loading Music": "Loading Music",
  Rockhopper: "Rockhopper",
  "Aunt Arctic": "Aunt Arctic",
  Cadence: "Cadence",
  Gary: "Gary",
  Franky: "Franky",
  "Petey K": "Petey K",
  "G Billy": "G Billy",
  "Stompin Bob": "Stompin Bob",
  Sensei: "Sensei",
  page: "Page",
  "new": "New",
  empty: "Empty",
  "Club Penguin": "Club Penguin",
  am: "am",
  pm: "pm",
  hour: "hour",
  hours: "hours",
  of: "of",
  Loading: "Loading",
  ninjaprogress: "Loading Ninja Progress",
  "Cards Collected: %0\nPPower Cards: %1 of %2": "Cards Collected: %0\nPower Cards: %1 of %2",
  "Current Belt": "Current Belt",
  "Next Belt": "Next Belt",
  "Current Item": "Current Item",
  "Next Item": "Next Item",
  sunday: "Sunday",
  monday: "Monday",
  tuesday: "Tuesday",
  wednesday: "Wednesday",
  thursday: "Thursday",
  friday: "Friday",
  saturday: "Saturday",
  binoculars: "Loading Binoculars",
  telescope: "Loading Telescope",
  map_note: "Click where you want to go.",
  map: "Loading Map",
  igloo_map: "Loading Igloo Map",
  load_penguin: "Loading Penguin",
  archives: "Loading Archives",
  ugc_wall: "Loading Art",
  load_mancala: "Loading Mancala",
  load_four: "Loading Find Four",
  load_aqua: "Loading Aqua Grabber",
  load_astro: "Loading Astro Barrier",
  load_beans: "Loading Beans",
  load_cart: "Loading Cart Surfer",
  load_fish: "Loading Gone Fishing",
  load_jetpack: "Loading Jet Pack Adventure",
  load_thinice: "Loading Thin Ice",
  load_waves: "Loading Catchin Waves",
  load_hydro: "Loading Hydro Hopper",
  load_pizzatron: "Loading Pizzatron 3000",
  load_roundup: "Loading Puffle Round-up",
  load_sled: "Loading Sled Racing",
  load_book1: "Loading Paint by Letters",
  load_book2: "Loading Paint by Letters",
  load_book3: "Loading Paint by Letters",
  load_mixmaster: "Loading DJ3K",
  load_treasurehunt: "Loading Treasure Hunt",
  load_balloon: "Loading Balloon Pop",
  load_bell: "Loading Ring The Bell",
  load_feed: "Loading Feed-A-Puffle",
  load_memory: "Loading Memory Card Game",
  load_paddle: "Loading Puffle Paddle",
  load_shuffle: "Loading Puffle Shuffle",
  load_soaker: "Loading Puffle Soaker",
  load_spin: "Loading Grab & Spin",
  load_card: "Loading Card-Jitsu",
  load_fire: "Loading Card-Jitsu Fire",
  load_water: "Loading Card-Jitsu Water",
  load_sensei: "Loading the Sensei",
  load_firesensei: "Loading the Sensei",
  load_watersensei: "Loading the Sensei",
  load_dancing: "Clearing the dance floor...",
  load_rescue: "Loading Puffle Rescue",
  load_systemdefend: "Loading System Defender",
  mancala: "Mancala",
  four: "Find Four",
  sled: "Sled Racing",
  treasurehunt: "Treasure Hunt",
  card: "Card-Jitsu",
  fire: "Card-Jitsu Fire",
  water: "Card-Jitsu Water",
  dancing: "Dance Contest",
  Settings: "Settings",
  "Youre on %servername%": "You\'re on %servername%",
  "Your penguin is %0 %1 old": "Your penguin is %0 %1 old",
  "Mute Music": "Mute Music",
  "Manage Account": "Manage Account",
  Buddies: "Buddies",
  igloo_contest: "Igloo Contest",
  igloo_contest_thanks: "Igloo Contest",
  igloo_background: "Igloo Background",
  igloo_storage: "Igloo Storage",
  "Open Igloos": "Open Igloos",
  load_mission1: "Loading Mission",
  load_mission2: "Loading Mission",
  load_mission3: "Loading Mission",
  load_mission4: "Loading Mission",
  load_mission5: "Loading Mission",
  load_mission6: "Loading Mission",
  load_mission7: "Loading Mission",
  load_mission8: "Loading Mission",
  load_mission9: "Loading Mission",
  load_mission10: "Loading Mission",
  load_mission11: "Loading Mission",
  load_town: "Loading Town",
  load_coffee: "Loading Coffee Shop",
  load_book: "Loading Book Room",
  load_dance: "Loading Dance Club",
  load_lounge: "Loading Dance Lounge",
  load_shop: "Loading Gift Shop",
  load_village: "Loading Ski Village",
  load_lodge: "Loading Ski Lodge",
  load_attic: "Loading Lodge Attic",
  load_sport: "Loading Sport Shop",
  load_mtn: "Loading Mountain",
  load_plaza: "Loading the Plaza",
  load_pet: "Loading the Pet Shop",
  load_dojo: "Loading the Dojo",
  load_dojoext: "Loading the Dojo Courtyard",
  load_dojohide: "Loading the Ninja Hideout",
  load_dojofire: "Loading the Fire Dojo",
  load_dojowater: "Loading Water Dojo",
  load_pizza: "Loading the Pizza Parlor",
  load_stage: "Loading the Stage",
  load_beach: "Loading Beach",
  load_light: "Loading Lighthouse",
  load_beacon: "Loading Beacon",
  load_ship: "Loading Pirate Ship",
  load_shiphold: "Loading Ship Hold",
  load_shipquarters: "Loading Captain\'s Quarters",
  load_shipnest: "Loading Crow\'s Nest",
  load_dock: "Loading the Dock",
  load_forts: "Loading Snow Forts",
  load_rink: "Loading Stadium",
  load_agent: "Loading HQ",
  load_agentcom: "Loading EPF Command Room",
  load_agentlobbysolo: "Loading the Facility",
  load_agentlobbymulti: "Loading the Phoning Facility",
  load_agentvr: "Loading the VR Room",
  load_boiler: "Loading Boiler Room",
  load_berg: "Loading the Iceberg",
  load_cave: "Loading Cave",
  load_mine: "Loading Mine",
  load_shack: "Loading Mine Shack",
  load_forest: "Loading Forest",
  load_cove: "Loading the Cove",
  load_boxdimension: "Loading Box Dimension",
  load_cavemine: "Loading Cave Mine",
  load_lake: "Loading the Hidden Lake",
  load_underwater: "Loading Underwater Room",
  load_eco: "Loading Recycling Plant",
  load_party: "Loading Sleigh",
  load_party1: "Loading Hoedown",
  load_party2: "Loading Haunted House",
  load_party3: "Loading Dark Swamp",
  load_party4: "Loading Dark Chamber",
  load_party5: "Loading Monster Room",
  load_party6: "Loading",
  load_party7: "Loading",
  load_party8: "Loading",
  load_party9: "Loading",
  load_party10: "Loading",
  load_party11: "Loading",
  load_party12: "Loading",
  load_party13: "Loading",
  load_party14: "Loading",
  load_party15: "Loading",
  load_party16: "Loading",
  load_party17: "Loading",
  load_party18: "Loading",
  load_party99: "Loading ???",
  pins_category_title: "Pins",
  pin_release_date: "Released: %month% %day%/%year%.",
  all_stamps_category_title: "All Stamps",
  colour: "Color",
  highlight: "Highlight",
  pattern: "Pattern",
  icon: "Icon",
  numerator_over_denominator: "%0/%1",
  total_stamps_label: "Total Stamps:",
  page_number: "Page\n%0 of %1",
  users_pins_label: "Your Pins:",
  recently_earned_title: "Your New Stamps",
  recently_earned_description: "These are your recently earned stamps:",
  recently_earned_congrats_single_stamp: "Congratulations on earning\n %0 stamp!",
  recently_earned_congrats_multiple_stamp: "Congratulations on earning\n %0 stamps!",
  total_stamps: "Total Stamps %0/%1",
  category_stamps_label: "%name% Stamps:",
  category_label: "%name%:",
  contents_category_title: "Contents",
  cover: "Cover",
  toc_legend_title: "Stamp Book Guide",
  toc_legend_easy: "Easy",
  toc_legend_medium: "Medium",
  toc_legend_hard: "Hard",
  toc_legend_extreme: "Extreme",
  toc_legend_member: "Member Stamp",
  toc_legend_new: "New Stamp",
  toc_legend_edit: "Edit Stamp Book",
  toc_legend_save: "Save Stamp Book",
  ping_release_date: "Released: %month%/%day%/%year%.",
  load_stampbook: "Loading Stampbook",
  "Loading StampBook": "Loading Stampbook",
  end_game_earned: "You\'ve earned:",
  end_game_coins_earned: "%num% coins",
  end_game_coins_earned_double: "%num% x 2 = %num_x2% coins",
  end_game_one_coin_earned: "1 coin",
  end_game_total_coins: "Your total coins: %num%",
  end_game_stamps_earned: "%num% of %total%",
  end_game_first_congrats: "Congratulations, all %game_name% stamps earned. Double coin bonus!",
  end_game_congrats: "Congratulations, double coin bonus!",
  end_game_howto_title: "Earn Stamps!",
  end_game_howto_btn: "How to earn stamps",
  game_name_stamps: "%game_name% Stamps",
  stamp_earned: "Stamp Earned!",
  end_game_no_coins_congrats: "Congratulations, all %game_name% stamps earned.",
  percent: "%percentage%%",
  stamp_book_hint: "Stamp Book",
  widget_stamps: "Your Stamps: %numerator%/%denominator%",
  "801_award": "Loading Award",
  "802_award": "Loading Award",
  "803_award": "Loading Award",
  "804_award": "Loading Award",
  "805_award": "Loading Award",
  "806_award": "Loading Award",
  "807_award": "Loading Forest Map",
  "808_award": "Loading Award",
  "809_award": "Loading Award",
  "810_award": "Loading Award",
  "811_award": "Loading Award",
  "812_award": "Loading Thank You Card",
  "813_award": "Loading Award",
  "814_award": "Loading Award",
  "815_award": "Loading Award",
  "816_award": "Loading Award",
  "817_award": "Loading Award",
  "818_award": "Loading Award",
  "819_award": "Loading Award",
  "820_award": "Loading Award",
  "821_award": "Loading Starter Deck",
  "822_award": "Loading Award",
  "823_award": "Loading Award",
  "8000_award": "Loading Wood EPF Badge",
  "8001_award": "Loading Ice EPF Badge",
  "8002_award": "Loading Bronze EPF Badge",
  "8003_award": "Loading Silver EPF Badge",
  "8004_award": "Loading Gold EPF Badge",
  "8005_award": "Loading EPF Certificate",
  "8006_award": "Loading Fire Booster Deck",
  "8007_award": "Loading Award",
  "8008_award": "Loading Award",
  "8010_award": "Loading Water Booster Deck",
  stowaway_book: "Loading Stowaway",
  franky_book: "Loading Franky",
  spice_book: "Loading Spice",
  dare_book: "Loading Dare",
  journal_book: "Loading Journal",
  tales07_book: "Loading Tales \'07",
  tales08_book: "Loading Tales \'08",
  tales09_book: "Loading Tales \'09",
  year0506_book: "Loading Yearbook 05/06",
  year0607_book: "Loading Yearbook 06/07",
  year0708_book: "Loading Yearbook 07/08",
  year0809_book: "Loading Yearbook 08/09",
  year0910_book: "Loading Yearbook 09/10",
  xmas_book1: "Loading Christmas Carol",
  xmas_book2: "Loading Rockhopper Island",
  xmas_book3: "Loading Music Makes Magic",
  fairyfables: "Loading Fairy Fables",
  give_tour: "Give a Tour",
  clothing_catalogue: "Loading Clothing Catalog",
  costume_catalogue: "Loading Costume Catalog",
  sport_catalogue: "Loading Sport Catalog",
  hair_catalogue: "Loading Hair Catalog",
  fish_catalogue: "Loading FISH Catalog",
  pets_catalogue: "Loading Puffle Catalog",
  adopt_catalogue: "Loading Puffle Catalog",
  pirate_catalogue: "Loading Pirate Catalog",
  igloo_catalogue: "Loading Igloo Catalog",
  furniture_catalogue: "Loading Furniture Catalog",
  music_catalogue: "Loading Music Catalog",
  merch_catalogue: "Loading Merchandise Catalog",
  merch_catalog: "Loading Merchandise Catalog",
  prizebooth: "Loading Prize Booth",
  prizeboothmember: "Loading Member Prize Booth",
  ninja_catalogue: "Loading Ninja Catalog",
  cove_catalogue: "Loading Cove Catalog",
  dock_catalogue: "Loading Dock Catalog",
  lodge_catalogue: "Loading Lodge Catalog",
  mtn_catalogue: "Loading Ski Hill Catalog",
  lake_catalogue: "Loading Diving Catalog",
  dance_catalogue: "Loading Dance Catalog",
  party_catalogue: "Loading Catalog",
  light_catalogue: "Loading Lighthouse Catalog",
  prizeBooth: "Loading Prize Booth",
  PrizeBoothMember: "Loading Member Prize Booth",
  clock_help: "Loading Clock Tower Plaque",
  backstage: "Loading Backstage Note",
  rockhopper_note: "Loading Rockhopper\'s Note",
  labcoat: "Loading Secret Lab Note",
  ninjabelts: "Loading Ninja Belts Legend",
  sensei_note: "Loading Sensei\'s Note",
  colour_poster: "Loading Color Poster",
  corkboard: "Loading Corkboard",
  take_tour: "Take a Tour",
  halloween_poster: "Haunted House Poster",
  fire_path_note: "Loading Sensei\'s Note",
  water_path_note: "Loading Sensei\'s Note",
  fireclothing: "Loading Fire Clothing Poster",
  waterclothing: "Loading Water Clothing Poster",
  maze_map: "Loading Maze Map",
  ninja_fire_video: "Loading Video",
  ninja_water_video: "Loading Video",
  water_path_video_flv: "Loading Video",
  christmasposter: "Loading Christmas Poster",
  splunkposter: "Loading Dig Poster",
  splunkposter2: "Loading Dig Poster",
  treasurepin1: "Loading Treasure",
  treasurepin2: "Loading Treasure",
  treasurepin3: "Loading Treasure",
  treasurepin4: "Loading Treasure",
  underwater_note: "Loading Note",
  goldenPuffleShort: "Loading Video",
  rubyShort: "Loading Video",
  fairyFablesShort: "Loading Video",
  penguinsTimeShort: "Loading Video",
  squidzoidShort: "Loading Video",
  underwaterShort: "Loading Video",
  poster: "Loading Poster",
  halloweenposter: "Loading Poster",
  instructions_quest: "Loading Quest Poster",
  InstructionsScroll: "Loading Ship Poster",
  InstructionsScroll2: "Loading Dragon Poster",
  party_poster: "Loading Poster",
  party_poster2: "Loading Pirate Poster",
  rink_poster: "Poster",
  party_note01: "Loading Note",
  party_note02: "Loading Note",
  party_note03: "Loading Note",
  party_note04: "Loading Note",
  party_note05: "Loading Note",
  mod_help: "Loading Moderator",
  egg_timer: "Loading Timer",
  help: "Loading Help",
  coins_for_change: "Loading Coins For Change",
  igloo_music: "Loading Music Menu",
  missions: "Loading Missions",
  agent_form: "Agent Form",
  news_form: "Newspaper Form",
  tour_form: "Tour Guide Form",
  report_form: "Report Form",
  penguintales: "Submission Form",
  library: "Loading Library",
  voting_booth: "Loading Voting Booth",
  "2009iceplaque_01": "Loading Sculpture Plaque",
  "2009iceplaque_02": "Loading Sculpture Plaque",
  "2009iceplaque_03": "Loading Sculpture Plaque",
  "2009iceplaque_04": "Loading Sculpture Plaque",
  "2009iceplaque_05": "Loading Sculpture Plaque",
  "2009iceplaque_06": "Loading Sculpture Plaque",
  "2009iceplaque_07": "Loading Sculpture Plaque",
  "2009iceplaque_08": "Loading Sculpture Plaque",
  "2009iceplaque_09": "Loading Sculpture Plaque",
  "2009iceplaque_10": "Loading Sculpture Plaque",
  "2009iceplaque_11": "Loading Sculpture Plaque",
  "2009iceplaque_12": "Loading Sculpture Plaque",
  "2009iceplaque_13": "Loading Sculpture Plaque",
  "2009iceplaque_14": "Loading Sculpture Plaque",
  "2009iceplaque_15": "Loading Sculpture Plaque",
  treasurehunt_help: "Loading Treasure Hunt Instructions",
  mancala_help: "Loading Mancala Instructions",
  instructions: "Loading Card-Jitsu Instructions",
  fireinstructions: "Loading Card-Jitsu Fire Instructions",
  waterinstructions: "Loading Instructions",
  oops_general: "Loading Membership",
  oops_inventory: "Loading Membership",
  oops_inventory_equip: "Loading Membership",
  oops_furniture: "Loading Membership",
  oops_igloo: "Loading Membership",
  oops_puffle: "Loading Membership",
  oops_game_dance: "Loading Membership",
  oops_game_dance_songs: "Loading Membership",
  oops_game_fire: "Loading Membership",
  oops_game_water: "Loading Membership",
  oops_party_room: "Loading Membership",
  oops_party2_room: "Loading Membership",
  oops_underwater_room: "Loading Membership",
  oops_game_rescue_level1: "Loading Membership",
  oops_game_rescue_level2: "Loading Membership",
  oops_party3_room: "Loading Membership",
  oops_party4_room: "Loading Membership",
  oops_party5_room: "Loading Membership",
  oops_party6_room: "Loading Membership",
  oops_party11_room: "Loading Membership",
  oops_party12_room: "Loading Membership",
  oops_party13_room: "Loading Membership",
  oops_party14_room: "Loading Membership",
  oops_puffle_whistle: "Loading Membership",
  oops_game_astrobarrier: "Loading Membership",
  oops_game_jetpack: "Loading Membership",
  oops_game_aquagrabber: "Loading Membership",
  oops_game_thinice: "Loading Membership",
  oops_game_waves_competition: "Loading Membership",
  oops_game_waves_survival: "Loading Membership",
  stampbook_cover_storage: "Loading Membership",
  oops_party11_catalog: "Loading Membership",
  login_membership_14: "Loading Membership",
  login_membership_7: "Loading Membership",
  login_membership_3: "Loading Membership",
  login_membership_2: "Loading Membership",
  login_membership_1: "Loading Membership",
  login_membership_expired: "Loading Membership",
  January: "January",
  February: "February",
  March: "March",
  April: "April",
  May: "May",
  June: "June",
  July: "July",
  August: "August",
  September: "September",
  October: "October",
  November: "November",
  December: "December",
  Day: "day",
  Days: "days",
  current_news: "Loading Newspaper",
  old_news0: "Loading Last Week\'s Issue",
  old_news1: "Loading Old Issue",
  old_news2: "Loading Old Issue",
  old_news3: "Loading Old Issue",
  old_news4: "Loading Old Issue",
  old_news5: "Loading Old Issue",
  scavenger_hunt: "Loading Scavenger Hunt",
  agent_line1: " ",
  agent_line2: " ",
  agent_line3: " ",
  agent_line4: " ",
  agentStatus: "Elite Gear",
  field_ops: "Field-Ops",
  fieldOps: "Field-Ops",
  puffle: "Elite Puffle",
  recruit: "Recruit",
  "Coming Soon": "Coming Soon",
  objectiveScreen: "Objective",
  epfmessage: "EPF Message",
  epfinitiated: "Congratulations",
  puffle_whistle: "Puffle Whistle Message",
  field_op_complete: "Field Op Complete",
  medal_earned: "Medal Earned!",
  communication: "Messages",
  public_computer_prompt_msg: "WAIT!\nDo other people use this computer?",
  save_password_warning_msg: "If you save your password here, anyone who uses this computer could access your account.",
  save_password: "Save Password",
  dont_save_password: "Don\'t Save Password",
  learn_more: "Learn More",
  player_safety_lose_coins: "They could spend your coins!",
  player_safety_changed_igloo: "They could change your igloo!",
  player_safety_banned: "They could get your penguin banned!"
}