import { StaticDataTable } from "../../common/static-table";

export type CardElement = 'f' | 's' | 'w';

export type CardColor = 'b' | 'g' | 'o' | 'p' | 'y' | 'r';

export type Card = {
  id: number,
  name: string,
  set: number,
  powerId: number,
  element: CardElement;
  color: CardColor
  value: number
  description: string
}

export const CARDS = new StaticDataTable<Card, [
  'id',
  'name',
  'set',
  'powerId',
  'element',
  'color',
  'value',
  'description'
]>([
  'id',
  'name',
  'set',
  'powerId',
  'element',
  'color',
  'value',
  'description'
], [
  [1, 'CART SURFER', 1, 0, 'f', 'b', 3, ''],
  [2, 'COFFEE SHOP', 1, 0, 'f', 'g', 2, ''],
  [3, 'ASTRO-BARRIER', 1, 0, 'f', 'g', 8, ''],
  [4, 'HOT CHOCOLATE', 1, 0, 'f', 'o', 3, ''],
  [5, 'LANDING PAD', 1, 0, 'f', 'p', 4, ''],
  [6, 'PIZZA CHEF', 1, 0, 'f', 'p', 6, ''],
  [7, 'PAINT BY LETTERS', 1, 0, 'f', 'r', 2, ''],
  [8, 'MINE', 1, 0, 'f', 'r', 7, ''],
  [9, 'CONSTRUCTION WORKER', 1, 0, 'f', 'y', 2, ''],
  [10, 'JET PACK ADVENTURE', 1, 0, 'f', 'y', 5, ''],
  [11, 'GIFT SHOP', 1, 0, 's', 'b', 3, ''],
  [12, 'HIKING IN THE FOREST', 1, 0, 's', 'g', 2, ''],
  [13, 'RESCUE SQUAD', 1, 0, 's', 'g', 5, ''],
  [14, 'PET SHOP', 1, 0, 's', 'o', 3, ''],
  [15, 'SKI VILLAGE', 1, 0, 's', 'p', 4, ''],
  [16, 'ICE HOCKEY', 1, 0, 's', 'p', 8, ''],
  [17, 'SKI HILL', 1, 0, 's', 'r', 2, ''],
  [18, 'SNOWBALL FIGHT', 1, 0, 's', 'r', 6, ''],
  [19, 'SNOW FORTS', 1, 0, 's', 'y', 2, ''],
  [20, 'SOCCER', 1, 0, 's', 'y', 7, ''],
  [21, 'BEACH', 1, 0, 'w', 'b', 3, ''],
  [22, 'FOOTBALL', 1, 0, 'w', 'b', 5, ''],
  [23, 'BASEBALL', 1, 0, 'w', 'g', 2, ''],
  [24, 'EMERALD PRINCESS', 1, 0, 'w', 'g', 8, ''],
  [25, 'BEAN COUNTERS', 1, 0, 'w', 'o', 3, ''],
  [26, 'MANHOLE COVER', 1, 0, 'w', 'p', 4, ''],
  [27, 'NEWSPAPER ARCHIVES', 1, 0, 'w', 'p', 6, ''],
  [28, 'UNDERGROUND POOL', 1, 0, 'w', 'r', 2, ''],
  [29, 'SCUBA DIVING', 1, 0, 'w', 'r', 7, ''],
  [30, 'ICE FISHING', 1, 0, 'w', 'y', 2, ''],
  [31, 'CASE OF THE MISSING COINS', 1, 0, 'f', 'b', 2, ''],
  [32, 'CRATES AND BOXES', 1, 0, 'f', 'b', 5, ''],
  [33, 'ANVIL SMITH', 1, 0, 'f', 'g', 4, ''],
  [34, 'HALLOWEEN', 1, 0, 'f', 'o', 6, ''],
  [35, 'KNIGHT', 1, 0, 'f', 'p', 3, ''],
  [36, 'BLACK PUFFLE', 1, 0, 'f', 'r', 5, ''],
  [37, 'MEDIEVAL PARTY', 1, 0, 'f', 'y', 4, ''],
  [38, 'BLUE PUFFLE', 1, 0, 's', 'b', 2, ''],
  [39, 'PINK PUFFLE', 1, 0, 's', 'b', 5, ''],
  [40, 'GREEN PUFFLE', 1, 0, 's', 'g', 4, ''],
  [41, 'PUFFLE FURNITURE', 1, 0, 's', 'o', 6, ''],
  [42, 'PURPLE PUFFLE', 1, 0, 's', 'p', 3, ''],
  [43, 'RED PUFFLE', 1, 0, 's', 'r', 5, ''],
  [44, 'YELLOW PUFFLE', 1, 0, 's', 'y', 4, ''],
  [45, 'SUMMER PARTY', 1, 0, 'w', 'b', 2, ''],
  [46, 'GRAY FISH', 1, 0, 'w', 'g', 4, ''],
  [47, 'O BERRY', 1, 0, 'w', 'o', 6, ''],
  [48, 'LIFE RING', 1, 0, 'w', 'p', 3, ''],
  [49, 'JOLLY ROGER FLAG', 1, 0, 'w', 'r', 5, ''],
  [50, 'COINS', 1, 0, 'w', 'y', 5, ''],
  [51, 'GARY THE GADGET GUY', 1, 0, 'f', 'b', 6, ''],
  [52, 'BUOYS', 1, 0, 'f', 'g', 5, ''],
  [53, 'YARR', 1, 0, 'f', 'o', 4, ''],
  [54, 'KLUTZY', 1, 0, 'f', 'p', 8, ''],
  [55, 'HERBERT P. BEAR', 1, 0, 'f', 'r', 3, ''],
  [56, 'HOT SAUCE', 1, 0, 'f', 'y', 7, ''],
  [57, 'SNOW CASTLE', 1, 0, 's', 'b', 6, ''],
  [58, 'AUNT ARCTIC', 1, 0, 's', 'g', 7, ''],
  [59, 'CHRISTMAS CAROLS', 1, 0, 's', 'o', 4, ''],
  [60, 'BETA PARTY', 1, 0, 's', 'o', 8, ''],
  [61, 'HIDDEN ITEMS', 1, 0, 's', 'p', 6, ''],
  [62, 'SECRET AGENT', 1, 0, 's', 'r', 3, ''],
  [63, 'SNOW SHOVEL', 1, 0, 's', 'y', 5, ''],
  [64, 'THE MIGRATOR', 1, 0, 'w', 'b', 6, ''],
  [65, 'CAPTAIN ROCKHOPPER', 1, 0, 'w', 'g', 5, ''],
  [66, 'ICE CREAM', 1, 0, 'w', 'o', 4, ''],
  [67, 'MULLET', 1, 0, 'w', 'p', 8, ''],
  [68, 'UNDERGROUND FLOOD', 1, 0, 'w', 'r', 3, ''],
  [69, 'FLUFFY THE FISH', 1, 0, 'w', 'y', 4, ''],
  [70, 'SHARK', 1, 0, 'w', 'y', 7, ''],
  [71, 'FLOORING UPGRADE', 1, 13, 'f', 'r', 9, 'When this is scored, Snow cannot be played next round.'],
  [72, 'GADGET ROOM', 1, 16, 'f', 'b', 9, 'When this is played, Water cards become Fire for this round.'],
  [73, 'JACKHAMMER', 1, 1, 'f', 'y', 10, 'When this card is played, lower values win ties the next round.'],
  [74, 'JET PACK', 1, 4, 'f', 'o', 10, 'When this is scored, discard one Opponent\'s Snowball card.'],
  [75, 'THIN ICE', 1, 7, 'f', 'p', 11, 'When this is scored, discard one Opponent\'s Red card.'],
  [76, 'NIGHT VISION GOGGLES', 1, 10, 'f', 'g', 11, 'When this is scored, discard one Opponent\'s Yellow card.'],
  [77, 'MIGHTY PLUNGER', 1, 2, 'f', 'r', 12, 'When this is scored, your card gets +2 for the next round'],
  [78, 'DRAGON', 1, 3, 'f', 'b', 12, 'When this is scored, your Opponent\'s card get -2 for the next round'],
  [79, 'SPACE ADVENTURE', 1, 15, 's', 'r', 9, 'When this is scored, Water cannot be played next round.'],
  [80, 'TOUR GUIDE', 1, 18, 's', 'b', 9, 'When this is played, Fire cards become Snowball for this round.'],
  [81, 'SLED RACING', 1, 1, 's', 'g', 10, 'When this card is played, lower values win ties the next round.'],
  [82, 'PUFFLE ROUND-UP', 1, 5, 's', 'g', 10, 'When this is scored, discard one Opponent\'s Water card.'],
  [83, 'AC3000', 1, 9, 's', 'p', 11, 'When this is scored, discard one Opponent\'s Green card.'],
  [84, 'SNOW GLOBE IGLOO', 1, 12, 's', 'y', 11, 'When this is scored, discard one Opponent\'s Purple card.'],
  [85, 'SHADOW GUY & GAMMA GAL', 1, 2, 's', 'o', 12, 'When this is scored, your card gets +2 for the next round'],
  [86, 'AVALANCHE', 1, 3, 's', 'o', 12, 'When this is scored, your Opponent\'s card get -2 for the next round'],
  [87, 'WATER PARTY', 1, 14, 'w', 'r', 9, 'When this is scored, Fire cannot be played next round.'],
  [88, 'CATCHIN\' WAVES', 1, 17, 'w', 'b', 9, 'When this is played, Snowball cards become Water for this round.'],
  [89, 'FIREFIGHTER', 1, 1, 'w', 'y', 10, 'When this card is played, lower values win ties the next round.'],
  [90, 'AQUA GRABBER', 1, 6, 'w', 'o', 10, 'When this is scored, discard one Opponent\'s Fire card.'],
  [91, 'OCTOPUS', 1, 8, 'w', 'p', 11, 'When this is scored, discard one Opponent\'s Blue card.'],
  [92, 'CACTUS', 1, 11, 'w', 'g', 11, 'When this is scored, discard one Opponent\'s Orange card.'],
  [93, 'TIPPING THE ICEBERG', 1, 2, 'w', 'p', 12, 'When this is scored, your card gets +2 for the next round'],
  [94, 'NINJA', 1, 3, 'w', 'y', 12, 'When this is scored, your Opponent\'s card get -2 for the next round'],
  [95, 'WHITE PUFFLE', 2, 10, 's', 'b', 12, 'When this is scored, discard one Opponent\'s Yellow card.'],
  [96, 'Yarr', 2, 4, 'f', 'r', 11, 'When this is scored, discard one Opponent\'s Snowball card.'],
  [97, 'KEEPER OF THE BOILER ROOM', 2, 9, 'w', 'g', 11, 'When this is scored, discard one Opponent\'s Green card.'],
  [98, 'BLAST', 2, 0, 'f', 'r', 8, ''],
  [99, 'FLARE', 2, 0, 'f', 'o', 7, ''],
  [100, 'CHIRP', 2, 0, 's', 'y', 6, ''],
  [101, 'POP', 2, 0, 'w', 'p', 5, ''],
  [102, 'LOOP', 2, 0, 'f', 'o', 7, ''],
  [103, 'FLIT', 2, 0, 's', 'g', 6, ''],
  [104, 'BOUNCER', 2, 0, 'w', 'b', 5, ''],
  [105, 'ED MCCOOL AND DESTRUCTO', 2, 0, 'f', 'b', 4, ''],
  [106, 'NIBLET', 2, 0, 'w', 'g', 2, ''],
  [107, 'SNOWY NIGHT', 2, 0, 's', 'p', 3, ''],
  [108, 'PUFFLES ON THE LOOSE', 2, 0, 'f', 'g', 4, ''],
  [109, 'CADENCE AND THE KEEPER', 2, 0, 'w', 'g', 3, ''],
  [110, 'GOLDEN PUFFLE', 2, 0, 's', 'y', 2, ''],
  [111, 'METEOR PUFFLE', 2, 0, 'f', 'r', 5, ''],
  [112, 'RAINBOW PUFFLE', 2, 0, 'w', 'p', 4, ''],
  [113, 'ABOMINABLE SNOW PUFFLE ', 2, 0, 's', 'o', 3, ''],
  [201, 'Club Penguin Times', 3, 0, 'f', 'b', 2, ''],
  [202, 'Can of Worms', 3, 0, 'f', 'b', 3, ''],
  [203, 'Winter Fiesta Party', 3, 0, 'f', 'p', 4, ''],
  [204, 'Invisible Ninja Suit', 3, 0, 'f', 'o', 5, ''],
  [205, 'Penguin Mail', 3, 0, 'f', 'r', 6, ''],
  [206, 'Bumble Bee', 3, 0, 'f', 'y', 6, ''],
  [207, 'Pizzatron 3000', 3, 0, 'f', 'o', 7, ''],
  [208, 'Card-Jitsu', 3, 0, 'f', 'r', 8, ''],
  [209, 'Adopt-A-Puffle', 3, 0, 's', 'b', 4, ''],
  [210, 'Rock & Roll Suit', 3, 0, 's', 'o', 4, ''],
  [211, 'Construction', 3, 0, 's', 'p', 5, ''],
  [212, 'Hidden Pins', 3, 0, 's', 'g', 6, ''],
  [213, 'Treasure Hunt Game', 3, 0, 's', 'y', 7, ''],
  [214, 'DJ3K', 3, 0, 's', 'g', 8, ''],
  [215, 'Surf Boards', 3, 0, 'w', 'g', 2, ''],
  [216, 'Beach Chair Chilling', 3, 0, 'w', 'g', 3, ''],
  [217, 'Telescope', 3, 0, 'w', 'r', 4, ''],
  [218, 'Fish Costume', 3, 0, 'w', 'y', 4, ''],
  [219, 'Crow\'s Nest', 3, 0, 'w', 'o', 5, ''],
  [220, 'The Cove', 3, 0, 'w', 'b', 6, ''],
  [221, 'Captain\'s Quarters', 3, 0, 'w', 'o', 6, ''],
  [222, 'Iceberg', 3, 0, 'w', 'b', 8, ''],
  [223, 'The Lounge', 3, 0, 'f', 'p', 3, ''],
  [224, 'Rockhopper\'s Key', 3, 0, 'f', 'g', 4, ''],
  [225, 'Penguins That Time Forgot', 3, 0, 'f', 'y', 5, ''],
  [226, 'Team Blue Rally', 3, 0, 'f', 'o', 6, ''],
  [227, 'Jet Pack Adventure', 3, 0, 'f', 'r', 7, ''],
  [228, 'Ruby and the Ruby', 3, 0, 's', 'r', 2, ''],
  [229, 'Snowball Fight', 3, 0, 's', 'o', 3, ''],
  [230, 'Snowball Press', 3, 0, 's', 'p', 5, ''],
  [231, 'Music Jam', 3, 0, 's', 'y', 6, ''],
  [232, 'Puffle Chew-Chew', 3, 0, 's', 'g', 7, ''],
  [233, 'Fairy Fables', 3, 0, 'w', 'g', 2, ''],
  [234, 'Jelly Fish', 3, 0, 'w', 'y', 3, ''],
  [235, 'Pirate', 3, 0, 'w', 'r', 4, ''],
  [236, 'Fish Bait', 3, 0, 'w', 'p', 5, ''],
  [237, 'Hydro Hopper', 3, 0, 'w', 'b', 7, ''],
  [238, 'Puffle O\'s', 3, 0, 'w', 'b', 7, ''],
  [239, 'Fall Fair Games', 3, 0, 'f', 'p', 4, ''],
  [240, 'Thinga-ma-jig 3000', 3, 0, 'f', 'g', 5, ''],
  [241, 'Rad Scientist', 3, 0, 's', 'r', 3, ''],
  [242, 'Quip and Qua', 3, 0, 's', 'b', 5, ''],
  [243, 'Twee', 3, 0, 's', 'p', 6, ''],
  [244, 'Coins For Change', 3, 0, 's', 'g', 8, ''],
  [245, 'Surfing with the Sharks', 3, 0, 'w', 'r', 5, ''],
  [246, 'Dance Contest', 3, 0, 'w', 'p', 6, ''],
  [247, 'Purple Octopus', 3, 0, 'w', 'p', 7, ''],
  [248, 'Giant Squid', 3, 0, 'w', 'b', 8, ''],
  [249, 'Penguin Band', 3, 16, 'f', 'b', 9, 'When this is played, Water cards become Fire for this round.'],
  [250, 'Dojo Sketch', 3, 13, 'f', 'y', 10, 'When this is scored, Snow cannot be played next round.'],
  [251, 'Flare Flinger 3000', 3, 7, 'f', 'p', 11, 'When this is scored, discard one Opponent\'s Red card.'],
  [252, 'Herbert & Klutzy', 3, 11, 'f', 'r', 12, 'When this is scored, discard one Opponent\'s Orange card.'],
  [253, 'Coffee Delivery Truck', 3, 15, 's', 'o', 9, 'When this is scored, Water cannot be played next round.'],
  [254, 'Anniversary Party', 3, 18, 's', 'b', 10, 'When this is played, Fire cards become Snowball for this round.'],
  [255, 'Halloween Party', 3, 5, 's', 'y', 11, 'When this is scored, discard one Opponent\'s Water card.'],
  [256, 'Sensei', 3, 12, 's', 'p', 12, 'When this is scored, discard one Opponent\'s Purple card.'],
  [257, 'Jackhammers', 3, 8, 'w', 'p', 9, 'When this is scored, discard one Opponent\'s Blue card.'],
  [258, 'Quest for the Golden Puffle', 3, 14, 'w', 'y', 10, 'When this is scored, Fire cannot be played next round.'],
  [259, 'Storm', 3, 6, 'w', 'o', 11, 'When this is scored, discard one Opponent\'s Fire card.'],
  [260, 'Rockhopper', 3, 17, 'w', 'b', 12, 'When this is played, Snowball cards become Water for this round.'],
  [301, 'Camera', 4, 0, 'f', 'o', 2, ''],
  [302, 'Wigs', 4, 0, 'f', 'b', 3, ''],
  [303, 'Pizza Parlor', 4, 0, 'f', 'r', 4, ''],
  [304, 'Coffee Machine', 4, 0, 'f', 'o', 5, ''],
  [305, 'Costume Trunk', 4, 0, 'f', 'r', 6, ''],
  [306, 'Pet Shop Staff', 4, 0, 'f', 'y', 6, ''],
  [307, 'Stompin\' Bob', 4, 0, 'f', 'o', 7, ''],
  [308, 'G Billy', 4, 0, 'f', 'r', 8, ''],
  [309, 'Outdoor Igloo', 4, 0, 's', 'b', 4, ''],
  [310, 'Ticket Booth', 4, 0, 's', 'o', 4, ''],
  [311, 'Ridge Run', 4, 0, 's', 'p', 5, ''],
  [312, 'Clock Tower', 4, 0, 's', 'g', 6, ''],
  [313, 'White Puffles', 4, 0, 's', 'y', 7, ''],
  [314, 'Dojo Courtyard', 4, 0, 's', 'g', 8, ''],
  [315, 'Rocking Horse', 4, 0, 'w', 'g', 2, ''],
  [316, 'Penguin Style', 4, 0, 'w', 'g', 3, ''],
  [317, 'Stage Director', 4, 0, 'f', 'r', 4, ''],
  [318, 'Conductor', 4, 0, 'w', 'y', 4, ''],
  [319, 'Beacon', 4, 0, 'w', 'o', 5, ''],
  [320, 'Discovering The Underground', 4, 0, 'f', 'o', 6, ''],
  [321, 'Franky', 4, 0, 'w', 'o', 6, ''],
  [322, 'Petey K.', 4, 0, 'w', 'b', 8, ''],
  [323, 'Boombox', 4, 0, 'f', 'p', 3, ''],
  [324, 'Mild Mannered Reporter', 4, 0, 'f', 'g', 4, ''],
  [325, 'The Twelfth Fish', 4, 0, 'f', 'y', 5, ''],
  [326, 'April Fool\'s Day Party', 4, 0, 'f', 'o', 6, ''],
  [327, 'Plasma Glow Wave', 4, 0, 'f', 'r', 7, ''],
  [328, 'Cowbell', 4, 0, 's', 'r', 2, ''],
  [329, 'O Berry Bush', 4, 0, 's', 'o', 3, ''],
  [330, 'Chester The Time Traveler', 4, 0, 's', 'r', 3, ''],
  [331, '101 Days of Fun', 4, 0, 's', 'r', 5, ''],
  [332, 'Color Vote', 4, 0, 's', 'y', 6, ''],
  [333, 'Christmas Party', 4, 0, 's', 'g', 7, ''],
  [334, 'Viking Opera', 4, 0, 'w', 'g', 2, ''],
  [335, 'Water Balloons', 4, 0, 'w', 'y', 3, ''],
  [336, 'Tuba', 4, 0, 'w', 'r', 4, ''],
  [337, 'Rockhopper\'s Plants', 4, 0, 'w', 'p', 5, ''],
  [338, 'Adventure Party', 4, 0, 'w', 'b', 7, ''],
  [339, 'Penguin Play Awards', 4, 0, 'f', 'o', 7, ''],
  [340, 'All-Access Pass', 4, 0, 'f', 'p', 4, ''],
  [341, 'Cadence\'s Autograph', 4, 0, 'f', 'g', 5, ''],
  [342, 'Treasure Book', 4, 0, 's', 'b', 5, ''],
  [343, 'Black Hoodie', 4, 0, 's', 'p', 6, ''],
  [344, 'Propellor Cap', 4, 0, 's', 'g', 8, ''],
  [345, 'Dessert Pizza', 4, 0, 'w', 'r', 5, ''],
  [346, 'Black Electric Guitar', 4, 0, 'w', 'r', 6, ''],
  [347, 'Mastering The Elements', 4, 0, 'w', 'p', 7, ''],
  [348, 'Elite Penguin Force', 4, 0, 'w', 'b', 8, ''],
  [349, 'Switchbox 3000', 4, 7, 'f', 'b', 11, 'When this is scored, discard one Opponent\'s Red card.'],
  [350, 'Medieval Party', 4, 8, 'f', 'y', 10, 'When this is scored, discard one Opponent\'s Blue card.'],
  [351, 'Cadence', 4, 3, 'f', 'r', 11, 'When this is scored, your Opponent\'s card get -2 for the next round'],
  [352, 'Cloud Wave', 4, 9, 'f', 'o', 12, 'When this is scored, discard one Opponent\'s Green card.'],
  [353, 'Ghost Sheet', 4, 3, 's', 'r', 12, 'When this is scored, your Opponent\'s card get -2 for the next round'],
  [354, 'Cart Surfer', 4, 12, 's', 'g', 10, 'When this is scored, discard one Opponent\'s Purple card.'],
  [355, 'Keytar', 4, 11, 's', 'p', 9, 'When this is scored, discard one Opponent\'s Orange card.'],
  [356, 'X-treme Jetpack', 4, 2, 's', 'y', 9, 'When this is scored, your card gets +2 for the next round'],
  [357, 'Box Dimension', 4, 2, 'w', 'b', 9, 'When this is scored, your card gets +2 for the next round'],
  [358, 'Gold Viking Helmet', 4, 10, 'w', 'p', 10, 'When this is scored, discard one Opponent\'s Yellow card.'],
  [359, 'Gary The Gadget Guy', 4, 2, 'w', 'o', 11, 'When this is scored, your card gets +2 for the next round'],
  [360, 'Rockhopper\'s Cannon', 4, 3, 'w', 'g', 12, 'When this is scored, your Opponent\'s card get -2 for the next round'],
  [401, 'Multi-Player', 5, 0, 'w', 'r', 2, ''],
  [402, 'Fire Battle', 5, 0, 'f', 'b', 3, ''],
  [403, 'Fired Up', 5, 0, 's', 'p', 4, ''],
  [404, 'Goldsmith', 5, 0, 'w', 'g', 2, ''],
  [405, 'Scroll', 5, 0, 'f', 'y', 3, ''],
  [406, 'Volcano', 5, 0, 's', 'o', 4, ''],
  [407, 'Ready For Battle', 5, 0, 'w', 'b', 2, ''],
  [408, 'Flying Flippers Emporium', 5, 0, 'f', 'p', 3, ''],
  [409, 'Duel', 5, 0, 's', 'g', 4, ''],
  [410, 'Concentrate', 5, 0, 'w', 'o', 2, ''],
  [411, 'Interior Construction', 5, 0, 'f', 'r', 3, ''],
  [412, 'Elements Hideout', 5, 0, 's', 'y', 4, ''],
  [413, 'Scavenger Hunt', 5, 0, 'w', 'r', 5, ''],
  [414, 'Fire Wheel', 5, 0, 'f', 'b', 6, ''],
  [415, 'Amulet Construction', 5, 0, 's', 'p', 5, ''],
  [416, 'Fire Dance', 5, 0, 'w', 'g', 6, ''],
  [417, 'Sketched Action', 5, 0, 'f', 'y', 5, ''],
  [418, 'Fire Guardian', 5, 0, 's', 'o', 6, ''],
  [419, 'Hot Sauce Reserve', 5, 0, 'w', 'r', 5, ''],
  [420, 'Sketched: Volcano', 5, 0, 'f', 'b', 6, ''],
  [421, 'Orange Sky', 5, 0, 'w', 'r', 7, ''],
  [422, 'Sketched: Enter', 5, 0, 'w', 'b', 8, ''],
  [423, 'Amulet', 5, 0, 'f', 'p', 9, ''],
  [424, 'A New Journey', 5, 0, 'f', 'g', 7, ''],
  [425, 'Fire Door & Key', 5, 0, 's', 'y', 8, ''],
  [426, 'Sensei Fire', 5, 0, 's', 'o', 9, ''],
  [427, 'Fire Ninja', 5, 4, 'f', 'r', 12, 'When this is scored, discard one Opponent\'s Snowball card.'],
  [501, 'Monkey King', 6, 0, 'f', 'b', 2, ''],
  [502, 'Jet Pack Pilot', 6, 0, 'f', 'b', 3, ''],
  [503, 'Fairy Princess', 6, 0, 'f', 'p', 4, ''],
  [504, 'Puffle Grooming', 6, 0, 'f', 'o', 5, ''],
  [505, 'Halloween Costumes', 6, 0, 'f', 'r', 6, ''],
  [506, 'Costume Show', 6, 0, 'f', 'y', 6, ''],
  [507, 'Soccer Match', 6, 0, 'f', 'o', 7, ''],
  [508, 'Bean Counters', 6, 0, 'f', 'b', 2, ''],
  [509, 'Earth Day Recycling', 6, 0, 'f', 'b', 3, ''],
  [510, 'Penguin Play Awards', 6, 0, 'f', 'p', 4, ''],
  [511, 'Goal!', 6, 0, 'f', 'o', 5, ''],
  [512, 'Bamboo Forest Sketch', 6, 0, 'f', 'r', 6, ''],
  [513, 'The Mine Cave is Safe!', 6, 0, 'f', 'y', 6, ''],
  [514, 'Mine Cave Construction', 6, 0, 'f', 'o', 7, ''],
  [515, 'Guardian Dog', 6, 0, 's', 'b', 4, ''],
  [516, 'The Fair', 6, 0, 's', 'o', 4, ''],
  [517, 'Hockey Gear', 6, 0, 's', 'p', 5, ''],
  [518, 'Puffle Show', 6, 0, 's', 'g', 6, ''],
  [519, 'Holiday Gifts', 6, 0, 's', 'y', 7, ''],
  [520, 'Holiday Activities', 6, 0, 's', 'g', 8, ''],
  [521, 'Stadium', 6, 0, 's', 'b', 4, ''],
  [522, 'Igloo Items', 6, 0, 's', 'o', 4, ''],
  [523, 'Music Jam', 6, 0, 's', 'p', 5, ''],
  [524, 'Elite Penguin Sketch', 6, 0, 's', 'g', 6, ''],
  [525, 'Festival of Flight', 6, 0, 'w', 'g', 2, ''],
  [526, 'Test Glider', 6, 0, 'w', 'g', 3, ''],
  [527, 'Puffle Paddle', 6, 0, 'w', 'r', 4, ''],
  [528, 'Fancy Formal Wear', 6, 0, 'w', 'y', 4, ''],
  [529, 'The Docks', 6, 0, 'w', 'o', 5, ''],
  [530, 'Orange Puffle', 6, 0, 'w', 'b', 6, ''],
  [531, 'Community Tree', 6, 0, 'w', 'o', 6, ''],
  [532, 'Community Garden', 6, 0, 'w', 'b', 8, ''],
  [533, 'Island Adventure Party', 6, 0, 'w', 'g', 2, ''],
  [534, 'Shops in Igloos', 6, 0, 'w', 'g', 3, ''],
  [535, 'Seafarer\'s Gown', 6, 0, 'w', 'r', 4, ''],
  [536, 'Music Jam Dancers', 6, 0, 'w', 'y', 4, ''],
  [537, 'Music Jam Rock Stage', 6, 0, 'w', 'o', 5, ''],
  [538, 'Music Jam Pop Stage', 6, 0, 'w', 'b', 6, ''],
  [539, 'Underwater Adventure', 6, 0, 'w', 'o', 6, ''],
  [540, 'Norman Swarm', 6, 0, 'w', 'b', 8, ''],
  [541, 'Puffle Rescuer', 6, 0, 'w', 'g', 2, ''],
  [542, 'Everyday Phoning Facility', 6, 0, 'w', 'g', 3, ''],
  [543, 'Jet Packs', 6, 0, 'f', 'p', 3, ''],
  [544, 'Pumpkin Igloo', 6, 0, 'f', 'g', 4, ''],
  [545, 'Treasure Hunt Adventure', 6, 0, 'f', 'y', 5, ''],
  [546, 'Destroyed PSA HQ', 6, 0, 'f', 'o', 6, ''],
  [547, 'Captains', 6, 0, 'f', 'r', 7, ''],
  [548, 'April Fools', 6, 0, 'f', 'r', 7, ''],
  [549, 'The Great Snow Maze', 6, 0, 's', 'r', 2, ''],
  [550, 'Jacques Hammer', 6, 0, 's', 'o', 3, ''],
  [551, 'Throne of April Fools', 6, 0, 's', 'p', 5, ''],
  [552, 'The Test', 6, 0, 's', 'g', 7, ''],
  [553, 'Cloud Maker 3000', 6, 0, 'w', 'g', 2, ''],
  [554, 'Super Exclusives', 6, 0, 'w', 'y', 3, ''],
  [555, 'Rockslide at the Mine', 6, 0, 'w', 'r', 4, ''],
  [556, 'Mer-penguins', 6, 0, 'w', 'p', 5, ''],
  [557, 'Puffer Fish', 6, 0, 'w', 'b', 7, ''],
  [558, 'Garden Hose', 6, 0, 'w', 'b', 7, ''],
  [559, 'Fixing the Mine Shack', 6, 0, 'w', 'b', 7, ''],
  [560, 'Puffle Circus', 6, 0, 'f', 'p', 4, ''],
  [561, 'Puffle Play Sketch', 6, 0, 'f', 'g', 5, ''],
  [562, 'Dragon Statue', 6, 0, 'f', 'p', 4, ''],
  [563, 'Popcorn Party', 6, 0, 'f', 'g', 5, ''],
  [564, 'White Puffle Room', 6, 0, 's', 'r', 3, ''],
  [565, 'Green Puffle Sketch', 6, 0, 's', 'b', 5, ''],
  [566, 'Fishbowl Igloo', 6, 0, 's', 'p', 6, ''],
  [567, 'Ship Battle Adventure', 6, 0, 'w', 'r', 5, ''],
  [568, 'Elite Penguin Force', 6, 0, 'w', 'p', 6, ''],
  [569, 'Rockhopper\'s Notice Board', 6, 0, 'w', 'p', 7, ''],
  [570, 'Squid Lid', 6, 0, 'w', 'b', 8, ''],
  [571, 'Hidden Lake', 6, 0, 'w', 'b', 8, ''],
  [572, 'Orange Puffle Wagon', 6, 16, 'f', 'b', 9, 'When this is played, Water cards become Fire for this round.'],
  [573, 'Haunted House', 6, 13, 'f', 'y', 10, 'When this is scored, Snow cannot be played next round.'],
  [574, 'Fire Dragon', 6, 7, 'f', 'p', 11, 'When this is scored, discard one Opponent\'s Red card.'],
  [575, 'Puffle Rescue: Underground', 6, 11, 'f', 'r', 12, 'When this is scored, discard one Opponent\'s Orange card.'],
  [576, 'Double Necked Guitar', 6, 15, 's', 'o', 9, 'When this is scored, Water cannot be played next round.'],
  [577, 'Puffle Rescue: Ice Floes', 6, 18, 's', 'b', 10, 'When this is played, Fire cards become Snowball for this round.'],
  [578, 'Spy Phone', 6, 12, 's', 'y', 11, 'When this is scored, discard one Opponent\'s Purple card.'],
  [579, 'Dance Contest', 6, 5, 's', 'p', 12, 'When this is scored, discard one Opponent\'s Water card.'],
  [580, 'Crab Costume', 6, 8, 'w', 'p', 9, 'When this is scored, discard one Opponent\'s Blue card.'],
  [581, 'Puffle Washer', 6, 14, 'w', 'y', 10, 'When this is scored, Fire cannot be played next round.'],
  [582, 'Green Jackhammer', 6, 6, 'w', 'o', 11, 'When this is scored, discard one Opponent\'s Fire card.'],
  [583, 'The Veggie Villain', 6, 17, 'w', 'b', 12, 'When this is played, Snowball cards become Water for this round.'],
  [584, 'Island Lifter 3000', 6, 16, 'f', 'b', 9, 'When this is played, Water cards become Fire for this round.'],
  [585, 'Flare', 6, 13, 'f', 'y', 10, 'When this is scored, Snow cannot be played next round.'],
  [586, 'Popcorn Device', 6, 7, 'f', 'p', 11, 'When this is scored, discard one Opponent\'s Red card.'],
  [587, 'Field-Ops', 6, 11, 'f', 'r', 12, 'When this is scored, discard one Opponent\'s Orange card.'],
  [588, 'Recipe for Disaster', 6, 15, 's', 'o', 9, 'When this is scored, Water cannot be played next round.'],
  [589, 'Elite Agent', 6, 18, 's', 'b', 10, 'When this is played, Fire cards become Snowball for this round.'],
  [590, 'Aunt Arctic Sketch', 6, 12, 's', 'y', 11, 'When this is scored, discard one Opponent\'s purple card.'],
  [591, 'Yeti Cave', 6, 5, 's', 'p', 12, 'When this is scored, discard one Opponent\'s Water card.'],
  [592, 'Shocktopus', 6, 8, 'w', 'p', 9, 'When this is scored, discard one Opponent\'s Blue card.'],
  [593, 'Puffle Rescue: Underwater', 6, 14, 'w', 'y', 10, 'When this is scored, Fire cannot be played next round.'],
  [594, 'Hidden Lake Lock', 6, 6, 'w', 'o', 11, 'When this is scored, discard one Opponent\'s Fire card.'],
  [595, 'Knight\'s Quest', 6, 17, 'w', 'b', 12, 'When this is played, Snowball cards become Water for this round.'],
  [601, 'Spooky Igloo Contest', 7, 0, 'f', 'b', 2, ''],
  [602, 'Halloween Countdown!', 7, 0, 'f', 'b', 3, ''],
  [603, 'Stormy Skies', 7, 0, 'f', 'p', 4, ''],
  [604, '5th Anniversary Party', 7, 0, 'f', 'o', 5, ''],
  [605, '5th Anniversary Cake', 7, 0, 'f', 'r', 6, ''],
  [606, '5th Anniversary Yearbook', 7, 0, 'f', 'y', 6, ''],
  [607, 'Snowball Fight!', 7, 0, 'f', 'o', 7, ''],
  [608, 'Find Four', 7, 0, 'f', 'b', 2, ''],
  [609, 'Cozy Ski Lodge', 7, 0, 'f', 'b', 3, ''],
  [610, 'Holiday Decorations!', 7, 0, 'f', 'p', 4, ''],
  [611, 'Book Room Adventures', 7, 0, 'f', 'o', 5, ''],
  [612, 'Halloween Forest', 7, 0, 'f', 'r', 6, ''],
  [613, 'Brown Puffle Rocket', 7, 0, 'f', 'y', 6, ''],
  [614, 'Fun at the Fair!', 7, 0, 'f', 'o', 7, ''],
  [615, 'Ski Hill Challenge', 7, 0, 's', 'b', 4, ''],
  [616, 'Holiday Party Skating', 7, 0, 's', 'o', 4, ''],
  [617, 'Treasure!', 7, 0, 's', 'p', 5, ''],
  [618, 'Lumberjack Look', 7, 0, 's', 'g', 6, ''],
  [619, 'Pink Sparkle Snowshoes', 7, 0, 's', 'y', 7, ''],
  [620, 'Holiday Tree 2010', 7, 0, 's', 'g', 8, ''],
  [621, 'Fill the Lighthouse!', 7, 0, 's', 'b', 4, ''],
  [622, 'Wilderness Machine', 7, 0, 's', 'o', 4, ''],
  [623, 'Expedition Boat', 7, 0, 's', 'p', 5, ''],
  [624, 'Wilderness Expedition Cave', 7, 0, 's', 'g', 6, ''],
  [625, 'Water Party Prep', 7, 0, 'w', 'g', 2, ''],
  [626, 'Water Dance', 7, 0, 'w', 'g', 3, ''],
  [627, 'Stamp Collectors', 7, 0, 'w', 'r', 4, ''],
  [628, 'Explore the Wilderness', 7, 0, 'w', 'y', 4, ''],
  [629, 'Coins for Change 2010!', 7, 0, 'w', 'o', 5, ''],
  [630, 'Penguin Colors', 7, 0, 'w', 'b', 6, ''],
  [631, 'Fairy Fables', 7, 0, 'w', 'o', 6, ''],
  [632, 'Penguins That Time Forgot', 7, 0, 'w', 'b', 8, ''],
  [633, 'EPF Sketch', 7, 0, 'w', 'g', 2, ''],
  [634, 'Cove Stories', 7, 0, 'w', 'g', 3, ''],
  [635, 'Orange Circus Puffle', 7, 0, 'w', 'r', 4, ''],
  [636, 'Hydro Hopper', 7, 0, 'w', 'y', 4, ''],
  [637, 'Igloo Party!', 7, 0, 'w', 'o', 5, ''],
  [638, 'Life Underwater', 7, 0, 'w', 'b', 6, ''],
  [639, 'Herbert\'s Monologue', 7, 0, 'w', 'o', 6, ''],
  [640, 'Enemy Bots', 7, 0, 'w', 'b', 8, ''],
  [641, 'Paint By Letters', 7, 0, 'w', 'g', 2, ''],
  [642, 'Secret Agent', 7, 0, 'w', 'g', 3, ''],
  [643, 'Fireworks', 7, 0, 'f', 'p', 3, ''],
  [644, 'EPF Tech Agent', 7, 0, 'f', 'g', 4, ''],
  [645, 'Popcorn Explosion', 7, 0, 'f', 'y', 5, ''],
  [646, 'Walk Your Puffle', 7, 0, 'f', 'o', 6, ''],
  [647, 'Sumo Smash', 7, 0, 'f', 'r', 7, ''],
  [648, 'inventive Brown Puffle', 7, 0, 'f', 'r', 7, ''],
  [649, 'Holiday Party Tree', 7, 0, 's', 'r', 2, ''],
  [650, 'EPF Enemies', 7, 0, 's', 'o', 3, ''],
  [651, 'Tall Tree Maze', 7, 0, 's', 'p', 5, ''],
  [652, 'Sled \'n Slide', 7, 0, 's', 'g', 7, ''],
  [653, 'Underwater at the Stage', 7, 0, 'w', 'g', 2, ''],
  [654, 'Wilderness Expedition Travel', 7, 0, 'w', 'y', 3, ''],
  [655, 'Catch the Mullet!', 7, 0, 'w', 'r', 4, ''],
  [656, 'Great Puffle Circus', 7, 0, 'w', 'p', 5, ''],
  [657, 'Intense Black Puffle', 7, 0, 'w', 'b', 7, ''],
  [658, 'Brown Puffle Storyboard', 7, 0, 'w', 'b', 7, ''],
  [659, 'Java Jump', 7, 0, 'w', 'b', 7, ''],
  [660, 'Master the Elements', 7, 0, 'f', 'p', 4, ''],
  [661, 'Fairy Fables Stage', 7, 0, 'f', 'g', 5, ''],
  [662, 'Creative Puffles', 7, 0, 'f', 'p', 4, ''],
  [663, 'Goofy Green Puffle', 7, 0, 'f', 'g', 5, ''],
  [664, 'EPF Test Room', 7, 0, 's', 'r', 3, ''],
  [665, 'Snowball Battle', 7, 0, 's', 'b', 5, ''],
  [666, 'Fabulous Purple Puffle', 7, 0, 's', 'p', 6, ''],
  [667, 'Water Party Sketch', 7, 0, 'w', 'r', 5, ''],
  [668, 'Zany Orange Puffle', 7, 0, 'w', 'p', 6, ''],
  [669, 'Sporty Pink Puffle', 7, 0, 'w', 'p', 7, ''],
  [670, 'Wii Game Day goal!', 7, 0, 'w', 'b', 8, ''],
  [671, 'Epic White Puffle', 7, 0, 'w', 'b', 8, ''],
  [672, 'Awesome Blue Puffle', 7, 0, 'f', 'b', 9, ''],
  [673, 'feed a _puffle', 7, 0, 'f', 'y', 9, ''],
  [674, 'Ninja Battle', 7, 0, 'f', 'b', 2, ''],
  [675, 'The Mystery of Sensei', 7, 0, 'f', 'p', 4, ''],
  [676, 'Master the Elements', 7, 0, 'f', 'o', 5, ''],
  [677, 'Brown Puffle', 7, 0, 'f', 'r', 6, ''],
  [678, 'Fire Wave', 7, 0, 'f', 'y', 6, ''],
  [679, 'Black Puffles in Cart Surfer', 7, 0, 'f', 'o', 7, ''],
  [680, 'Mountain Expedition', 7, 0, 's', 'b', 4, ''],
  [681, 'Climbing the Mountain', 7, 0, 's', 'o', 4, ''],
  [682, 'Top of Toughest Mountain', 7, 0, 's', 'p', 5, ''],
  [683, 'Cart Surfer Stamps', 7, 0, 's', 'g', 6, ''],
  [684, 'Stamp Book', 7, 0, 's', 'y', 7, ''],
  [685, 'Stormy Sky ', 7, 0, 's', 'g', 8, ''],
  [686, 'Water Wave Sketches', 7, 0, 's', 'b', 4, ''],
  [687, 'Storm Baffles Gary', 7, 0, 's', 'o', 4, ''],
  [688, 'Water Ninja', 7, 0, 'w', 'g', 3, ''],
  [689, 'The First Rainstorm', 7, 0, 'w', 'r', 4, ''],
  [690, 'Ninja Face-off', 7, 0, 'w', 'y', 4, ''],
  [691, 'Earning the Water Suit', 7, 0, 'w', 'o', 5, ''],
  [692, 'Water Pumping Gadget', 7, 0, 'w', 'b', 6, ''],
  [693, 'Preparing the Water Dojo', 7, 0, 'w', 'o', 6, ''],
  [694, 'Gate to the Water Dojo', 7, 0, 'w', 'b', 8, ''],
  [695, 'Water Suit', 7, 0, 'w', 'g', 2, ''],
  [696, 'Sign From The Elements', 7, 0, 'w', 'g', 3, ''],
  [697, 'Sensei - Master of Water', 7, 0, 'w', 'r', 4, ''],
  [698, 'Water Ninja Poster Sketch', 7, 0, 'w', 'y', 4, ''],
  [699, 'Water Ninja Sketch', 7, 0, 'w', 'o', 5, ''],
  [700, 'Water Beats Fire Sketch', 7, 0, 'f', 'p', 3, ''],
  [701, 'Blast', 7, 0, 'f', 'r', 8, ''],
  [702, 'Flare', 7, 0, 'f', 'o', 7, ''],
  [703, 'Chirp', 7, 0, 's', 'y', 6, ''],
  [704, 'Pop', 7, 0, 'w', 'p', 5, ''],
  [705, 'Loop', 7, 0, 'f', 'o', 7, ''],
  [706, 'Flit', 7, 0, 's', 'g', 6, ''],
  [707, 'Bouncer', 7, 0, 'w', 'b', 5, ''],
  [708, 'Ed McCool and Destructo', 7, 0, 'f', 'b', 4, ''],
  [709, 'Niblet', 7, 0, 'w', 'g', 2, ''],
  [710, 'Snowy Night', 7, 0, 's', 'p', 3, ''],
  [711, 'Puffles on the Loose', 7, 0, 'f', 'g', 4, ''],
  [712, 'Cadence and the Keeper', 7, 0, 'w', 'g', 3, ''],
  [713, 'Golden puffle', 7, 0, 's', 'y', 2, ''],
  [714, 'Meteor puffle', 7, 0, 'f', 'r', 5, ''],
  [715, 'Rainbow puffle', 7, 0, 'w', 'p', 4, ''],
  [716, 'Abominable snow puffle', 7, 0, 's', 'o', 3, ''],
  [717, 'Black Puffle', 7, 0, 'f', 'r', 5, ''],
  [718, 'Blue Puffle', 7, 0, 's', 'b', 2, ''],
  [719, 'Pink Puffle', 7, 0, 's', 'b', 5, ''],
  [720, 'Green Puffle', 7, 0, 's', 'g', 4, ''],
  [721, 'Purple Puffle', 7, 0, 's', 'p', 3, ''],
  [722, 'Red Puffle', 7, 0, 's', 'r', 5, ''],
  [723, 'Yellow Puffle', 7, 0, 's', 'y', 4, ''],
  [724, 'Puffle Round Up', 7, 5, 's', 'g', 10, 'When this is scored, discard one opponent\'s Water card.'],
  [725, 'Fire Ninja Force', 7, 11, 'f', 'r', 12, 'When this is scored, discard one opponent\'s Orange card.'],
  [726, 'Halloween Swamp', 7, 15, 's', 'o', 9, 'When this is scored, Water cannot be played next round.'],
  [727, 'Prepare for Pumpkins', 7, 17, 's', 'b', 10, 'When this is played, Snowball cards become Fire for this round'],
  [728, 'Finding Rockhopper', 7, 12, 's', 'y', 11, 'When this is scored, discard one opponent\'s Purple card.'],
  [729, 'Elite Puffle: Flare', 7, 5, 's', 'p', 12, 'When this is scored, discard one opponent\'s Water card.'],
  [730, 'Giant Pearl', 7, 8, 'w', 'p', 9, 'When this is scored, discard one opponent\'s Blue card.'],
  [731, 'Water Stamps', 7, 14, 'w', 'y', 10, 'When this is scored, Fire cannot be played next round.'],
  [732, 'EPF Agents', 7, 6, 'w', 'o', 11, 'When this is scored, discard one opponent\'s Fire card.'],
  [733, 'Puffle Rescue', 7, 17, 'w', 'b', 12, 'When this is played, Snowball cards become Water for this round.'],
  [734, 'Fire Dojo Challenge', 7, 16, 'f', 'b', 9, 'When this is played, Water cards become Fire for this round.'],
  [735, 'System Defender', 7, 13, 'f', 'y', 10, 'When this is scored, Snow cannot be played next round.'],
  [736, 'Adventurous Red Puffle', 7, 7, 'f', 'p', 11, 'When this is scored, discard one opponent\'s Red card.'],
  [737, 'G and the Machine', 7, 11, 'f', 'r', 12, 'When this is scored, discard one opponent\'s Orange card.'],
  [738, 'Enemies of the System', 7, 15, 's', 'o', 9, 'When this is scored, Water cannot be played next round.'],
  [739, 'Holiday Dojo Lights', 7, 18, 's', 'b', 10, 'When this is played, Fire cards become Snowball for this round.'],
  [740, 'Wii Rollin\' Riot', 7, 12, 's', 'y', 11, 'When this is scored, discard one opponent\'s Purple card.'],
  [741, 'EPF Under Attack', 7, 5, 's', 'p', 12, 'When this is scored, discard one opponent\'s Water card.'],
  [742, 'Elite Comm Class Agents', 7, 8, 'w', 'p', 9, 'When this is scored, discard one opponent\'s Blue card.'],
  [743, 'Brown Puffle Cliff', 7, 14, 'w', 'y', 10, 'When this is scored, Fire cannot be played next round.'],
  [744, 'Coins for Change Goal!', 7, 6, 'w', 'o', 11, 'When this is scored, discard one opponent\'s Fire card.'],
  [745, 'Sensei Water Battle ', 7, 14, 'w', 'b', 9, 'When this is played, Fire cards become Water for this round.'],
  [746, 'Green Puffles in Jet Pack Adve', 7, 13, 'f', 'y', 10, 'When this is scored, Snow cannot be played next round.'],
  [747, 'Water Dojo', 7, 7, 'w', 'p', 11, 'When this is scored, discard one opponent\'s Red card.'],
  [748, 'White Puffle', 7, 10, 's', 'b', 12, 'When this is scored, discard one opponent\'s Yellow card.'],
  [749, 'Yarr', 7, 4, 'f', 'r', 11, 'When this is scored, discard one opponent\'s Snowball card.'],
  [750, 'Keeper of the Boiler Room', 7, 9, 'w', 'g', 11, 'When this is scored, discard one opponent\'s Green card.'],
  [801, 'Mobile Fire 1', 8, 0, 'f', 'r', 6, ''],
  [802, 'Mobile Snow 1', 8, 0, 's', 'g', 7, ''],
  [803, 'Mobile Water 1', 8, 0, 'w', 'b', 8, ''],
  [804, 'Mobile Fire Power Card 1', 8, 2, 'f', 'p', 11, 'When this is scored, your card gets +2 for the next round']
]);